# Bringing in Data from Supabase

In [1]:
pip install supabase

Requirement already satisfied: supabase in /usr/local/lib/python3.12/dist-packages (2.28.3)
Requirement already satisfied: realtime==2.28.3 in /usr/local/lib/python3.12/dist-packages (from supabase) (2.28.3)
Requirement already satisfied: supabase-functions==2.28.3 in /usr/local/lib/python3.12/dist-packages (from supabase) (2.28.3)
Requirement already satisfied: storage3==2.28.3 in /usr/local/lib/python3.12/dist-packages (from supabase) (2.28.3)
Requirement already satisfied: supabase-auth==2.28.3 in /usr/local/lib/python3.12/dist-packages (from supabase) (2.28.3)
Requirement already satisfied: postgrest==2.28.3 in /usr/local/lib/python3.12/dist-packages (from supabase) (2.28.3)
Requirement already satisfied: httpx<0.29,>=0.26 in /usr/local/lib/python3.12/dist-packages (from supabase) (0.28.1)
Requirement already satisfied: yarl>=1.22.0 in /usr/local/lib/python3.12/dist-packages (from supabase) (1.23.0)
Requirement already satisfied: deprecation>=2.1.0 in /usr/local/lib/python3.12/dist-packages (from postgrest==2.28.3->supabase) (2.1.0)
Requirement already satisfied: pydantic<3.0,>=1.9 in /usr/local/lib/python3.12/dist-packages (from postgrest==2.28.3->supabase) (2.12.3)
Requirement already satisfied: typing-extensions>=4.14.0 in /usr/local/lib/python3.12/dist-packages (from realtime==2.28.3->supabase) (4.15.0)
Requirement already satisfied: websockets<16,>=11 in /usr/local/lib/python3.12/dist-packages (from realtime==2.28.3->supabase) (15.0.1)
Requirement already satisfied: pyiceberg>=0.10.0 in /usr/local/lib/python3.12/dist-packages (from storage3==2.28.3->supabase) (0.11.1)
Requirement already satisfied: pyjwt>=2.10.1 in /usr/local/lib/python3.12/dist-packages (from pyjwt[crypto]>=2.10.1->supabase-auth==2.28.3->supabase) (2.12.1)
Requirement already satisfied: strenum>=0.4.15 in /usr/local/lib/python3.12/dist-packages (from supabase-functions==2.28.3->supabase) (0.4.15)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<0.29,>=0.26->supabase) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<0.29,>=0.26->supabase) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<0.29,>=0.26->supabase) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<0.29,>=0.26->supabase) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<0.29,>=0.26->supabase) (0.16.0)
Requirement already satisfied: multidict>=4.0 in /usr/local/lib/python3.12/dist-packages (from yarl>=1.22.0->supabase) (6.7.1)
Requirement already satisfied: propcache>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from yarl>=1.22.0->supabase) (0.4.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from deprecation>=2.1.0->postgrest==2.28.3->supabase) (26.0)
Requirement already satisfied: h2<5,>=3 in /usr/local/lib/python3.12/dist-packages (from httpx[http2]<0.29,>=0.26->postgrest==2.28.3->supabase) (4.3.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0,>=1.9->postgrest==2.28.3->supabase) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0,>=1.9->postgrest==2.28.3->supabase) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0,>=1.9->postgrest==2.28.3->supabase) (0.4.2)
Requirement already satisfied: mmh3<6.0.0,>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from pyiceberg>=0.10.0->storage3==2.28.3->supabase) (5.2.1)
Requirement already satisfied: requests<3.0.0,>=2.20.0 in /usr/local/lib/python3.12/dist-packages (from pyiceberg>=0.10.0->storage3==2.28.3->supabase) (2.32.4)
Requirement already satisfied: click<9.0.0,>=7.1.1 in /usr/local/lib/python3.12/dist-packages (from pyiceberg>=0.10.0->storage3==2.28.3->supabase) (8.3.1)
Requirement already satisfied: rich<15.0.0,>=10.11.0 in /usr/local/lib/python3.12/dist-packages (from pyiceberg>=0.10.0->storage3==2.28.3->supabase) (13.9.4)
Requirement already satisfied: strictyaml<2.0.0,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from pyiceberg>=0.10.0->storage3==2.28.3->supabase) (1.7.3)
Requirement already satisfied: fsspec>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from pyiceberg>=0.10.0->storage3==2.28.3->supabase) (2025.3.0)
Requirement already satisfied: pyparsing<4.0.0,>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from pyiceberg>=0.10.0->storage3==2.28.3->supabase) (3.3.2)
Requirement already satisfied: tenacity<10.0.0,>=8.2.3 in /usr/local/lib/python3.12/dist-packages (from pyiceberg>=0.10.0->storage3==2.28.3->supabase) (9.1.4)
Requirement already satisfied: pyroaring<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from pyiceberg>=0.10.0->storage3==2.28.3->supabase) (1.0.4)
Requirement already satisfied: cachetools<7.0,>=5.5 in /usr/local/lib/python3.12/dist-packages (from pyiceberg>=0.10.0->storage3==2.28.3->supabase) (6.2.6)
Requirement already satisfied: zstandard<1.0.0,>=0.13.0 in /usr/local/lib/python3.12/dist-packages (from pyiceberg>=0.10.0->storage3==2.28.3->supabase) (0.25.0)
Requirement already satisfied: cryptography>=3.4.0 in /usr/local/lib/python3.12/dist-packages (from pyjwt[crypto]>=2.10.1->supabase-auth==2.28.3->supabase) (43.0.3)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.12/dist-packages (from cryptography>=3.4.0->pyjwt[crypto]>=2.10.1->supabase-auth==2.28.3->supabase) (2.0.0)
Requirement already satisfied: hyperframe<7,>=6.1 in /usr/local/lib/python3.12/dist-packages (from h2<5,>=3->httpx[http2]<0.29,>=0.26->postgrest==2.28.3->supabase) (6.1.0)
Requirement already satisfied: hpack<5,>=4.1 in /usr/local/lib/python3.12/dist-packages (from h2<5,>=3->httpx[http2]<0.29,>=0.26->postgrest==2.28.3->supabase) (4.1.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.20.0->pyiceberg>=0.10.0->storage3==2.28.3->supabase) (3.4.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.20.0->pyiceberg>=0.10.0->storage3==2.28.3->supabase) (2.5.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich<15.0.0,>=10.11.0->pyiceberg>=0.10.0->storage3==2.28.3->supabase) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich<15.0.0,>=10.11.0->pyiceberg>=0.10.0->storage3==2.28.3->supabase) (2.20.0)
Requirement already satisfied: python-dateutil>=2.6.0 in /usr/local/lib/python3.12/dist-packages (from strictyaml<2.0.0,>=1.7.0->pyiceberg>=0.10.0->storage3==2.28.3->supabase) (2.9.0.post0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.12->cryptography>=3.4.0->pyjwt[crypto]>=2.10.1->supabase-auth==2.28.3->supabase) (3.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich<15.0.0,>=10.11.0->pyiceberg>=0.10.0->storage3==2.28.3->supabase) (0.1.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.6.0->strictyaml<2.0.0,>=1.7.0->pyiceberg>=0.10.0->storage3==2.28.3->supabase) (1.17.0)

In [2]:
from supabase import create_client, Client
from google.colab import userdata

# Retrieve credentials from Colab secrets
SUPABASE_URL = userdata.get('SUPABASE_URL')
SUPABASE_KEY = userdata.get('SUPABASE_KEY')

# Create a Supabase client
supabase: Client = create_client(SUPABASE_URL, SUPABASE_KEY)

print("Supabase client created successfully.")

Supabase client created successfully.

In [3]:
import pandas as pd

response = supabase.table('articles_v1').select('*').execute()
data = response.data

# Convert the data to a pandas DataFrame for easier analysis
df = pd.DataFrame(data)

# Display the first few rows of the DataFrame
display(df.head())

,doc_id,source,source_type,publish_timestamp,title,raw_text,url,fetch_timestamp,raw_html
0,a5be497f1c586e6269c0609e6fb1f591d5afc3e5790743...,PYMNTS,news,2026-03-11T08:02:09+00:00,AI Forensics Takes Aim at Compliance Gridlock,AI Forensics Takes Aim at Compliance Gridlock ...,https://www.pymnts.com/news/artificial-intelli...,2026-03-11T09:01:44.489463+00:00,https://www.pymnts.com/news/artificial-intelli...
1,dd8ca37af85b6c3b9a9aa93cc6b381769dfe69e767e7b1...,PYMNTS,news,2026-03-11T08:00:40+00:00,47% of Merchants Report False Declines Cost Th...,47% of Merchants Report False Declines Cost Th...,https://www.pymnts.com/fraud-prevention/2026/4...,2026-03-11T09:01:44.489463+00:00,https://www.pymnts.com/fraud-prevention/2026/4...
2,1e1107dd8d70e1b2b4354cfb1a03f2fb89ef02cb846b38...,PYMNTS,news,2026-02-27T22:43:31+00:00,Morgan Stanley Wants to Build the Back Office ...,Morgan Stanley Wants to Build the Back Office ...,https://www.pymnts.com/cryptocurrency/2026/mor...,2026-03-02T09:01:44.601819+00:00,https://www.pymnts.com/cryptocurrency/2026/mor...
3,a2b322624c7eefbba1f180f64ad12964870b5ea570aaf7...,PYMNTS,news,2026-03-01T21:30:54+00:00,Apple Set to Announce AI-Native Hardware to Un...,Apple Set to Announce AI-Native Hardware to Un...,https://www.pymnts.com/apple/2026/apple-plans-...,2026-03-02T14:01:51.078611+00:00,https://www.pymnts.com/apple/2026/apple-plans-...
4,5e22f48845e7bac3e621e6fb1b0467eeecdacf9cff2a97...,PYMNTS,news,2026-02-28T01:19:27+00:00,Visa Closes Prisma and Newpay Acquisition to E...,Visa Closes Prisma and Newpay Acquisition to E...,https://www.pymnts.com/acquisitions/2026/visa-...,2026-03-02T14:01:51.078611+00:00,https://www.pymnts.com/acquisitions/2026/visa-...

In [4]:
df.shape

(937, 9)

In [5]:
print(f"Shape before removing duplicates: {df.shape}")
df.drop_duplicates(subset=['doc_id'], inplace=True)
print(f"Shape after removing duplicates: {df.shape}")
display(df.head())

Shape before removing duplicates: (937, 9)
Shape after removing duplicates: (937, 9)

,doc_id,source,source_type,publish_timestamp,title,raw_text,url,fetch_timestamp,raw_html
0,a5be497f1c586e6269c0609e6fb1f591d5afc3e5790743...,PYMNTS,news,2026-03-11T08:02:09+00:00,AI Forensics Takes Aim at Compliance Gridlock,AI Forensics Takes Aim at Compliance Gridlock ...,https://www.pymnts.com/news/artificial-intelli...,2026-03-11T09:01:44.489463+00:00,https://www.pymnts.com/news/artificial-intelli...
1,dd8ca37af85b6c3b9a9aa93cc6b381769dfe69e767e7b1...,PYMNTS,news,2026-03-11T08:00:40+00:00,47% of Merchants Report False Declines Cost Th...,47% of Merchants Report False Declines Cost Th...,https://www.pymnts.com/fraud-prevention/2026/4...,2026-03-11T09:01:44.489463+00:00,https://www.pymnts.com/fraud-prevention/2026/4...
2,1e1107dd8d70e1b2b4354cfb1a03f2fb89ef02cb846b38...,PYMNTS,news,2026-02-27T22:43:31+00:00,Morgan Stanley Wants to Build the Back Office ...,Morgan Stanley Wants to Build the Back Office ...,https://www.pymnts.com/cryptocurrency/2026/mor...,2026-03-02T09:01:44.601819+00:00,https://www.pymnts.com/cryptocurrency/2026/mor...
3,a2b322624c7eefbba1f180f64ad12964870b5ea570aaf7...,PYMNTS,news,2026-03-01T21:30:54+00:00,Apple Set to Announce AI-Native Hardware to Un...,Apple Set to Announce AI-Native Hardware to Un...,https://www.pymnts.com/apple/2026/apple-plans-...,2026-03-02T14:01:51.078611+00:00,https://www.pymnts.com/apple/2026/apple-plans-...
4,5e22f48845e7bac3e621e6fb1b0467eeecdacf9cff2a97...,PYMNTS,news,2026-02-28T01:19:27+00:00,Visa Closes Prisma and Newpay Acquisition to E...,Visa Closes Prisma and Newpay Acquisition to E...,https://www.pymnts.com/acquisitions/2026/visa-...,2026-03-02T14:01:51.078611+00:00,https://www.pymnts.com/acquisitions/2026/visa-...

In [6]:
import google.generativeai as genai
from google.colab import userdata

# Retrieve the Gemini API key from Colab secrets
GEMINI_API_KEY = userdata.get('GEMINI_API_KEY')

# Configure the google.generativeai library
genai.configure(api_key=GEMINI_API_KEY)

print("Gemini API key retrieved and Generative AI library configured.")

/usr/local/lib/python3.12/dist-packages/google/colab/_import_hooks/_hook_injector.py:55: FutureWarning:

All support for the `google.generativeai` package has ended. It will no longer be receiving
updates or bug fixes. Please switch to the `google.genai` package as soon as possible.
See README for more details:

https://github.com/google-gemini/deprecated-generative-ai-python/blob/main/README.md

  loader.exec_module(module)

Gemini API key retrieved and Generative AI library configured.

In [7]:
import re

def clean_text(text):
    if not isinstance(text, str):
        return ""
    # Convert to lowercase
    text = text.lower()
    # Remove special characters and numbers, keep only letters and spaces
    text = re.sub(r'[^a-z\s]', '', text)
    # Remove extra spaces
    text = re.sub(r'\s+', ' ', text).strip()
    return text

print("Text cleaning function 'clean_text' defined.")

Text cleaning function 'clean_text' defined.

In [8]:
df['cleaned_text'] = df['raw_text'].apply(clean_text)
display(df.head())

,doc_id,source,source_type,publish_timestamp,title,raw_text,url,fetch_timestamp,raw_html,cleaned_text
0,a5be497f1c586e6269c0609e6fb1f591d5afc3e5790743...,PYMNTS,news,2026-03-11T08:02:09+00:00,AI Forensics Takes Aim at Compliance Gridlock,AI Forensics Takes Aim at Compliance Gridlock ...,https://www.pymnts.com/news/artificial-intelli...,2026-03-11T09:01:44.489463+00:00,https://www.pymnts.com/news/artificial-intelli...,ai forensics takes aim at compliance gridlock ...
1,dd8ca37af85b6c3b9a9aa93cc6b381769dfe69e767e7b1...,PYMNTS,news,2026-03-11T08:00:40+00:00,47% of Merchants Report False Declines Cost Th...,47% of Merchants Report False Declines Cost Th...,https://www.pymnts.com/fraud-prevention/2026/4...,2026-03-11T09:01:44.489463+00:00,https://www.pymnts.com/fraud-prevention/2026/4...,of merchants report false declines cost them s...
2,1e1107dd8d70e1b2b4354cfb1a03f2fb89ef02cb846b38...,PYMNTS,news,2026-02-27T22:43:31+00:00,Morgan Stanley Wants to Build the Back Office ...,Morgan Stanley Wants to Build the Back Office ...,https://www.pymnts.com/cryptocurrency/2026/mor...,2026-03-02T09:01:44.601819+00:00,https://www.pymnts.com/cryptocurrency/2026/mor...,morgan stanley wants to build the back office ...
3,a2b322624c7eefbba1f180f64ad12964870b5ea570aaf7...,PYMNTS,news,2026-03-01T21:30:54+00:00,Apple Set to Announce AI-Native Hardware to Un...,Apple Set to Announce AI-Native Hardware to Un...,https://www.pymnts.com/apple/2026/apple-plans-...,2026-03-02T14:01:51.078611+00:00,https://www.pymnts.com/apple/2026/apple-plans-...,apple set to announce ainative hardware to unl...
4,5e22f48845e7bac3e621e6fb1b0467eeecdacf9cff2a97...,PYMNTS,news,2026-02-28T01:19:27+00:00,Visa Closes Prisma and Newpay Acquisition to E...,Visa Closes Prisma and Newpay Acquisition to E...,https://www.pymnts.com/acquisitions/2026/visa-...,2026-03-02T14:01:51.078611+00:00,https://www.pymnts.com/acquisitions/2026/visa-...,visa closes prisma and newpay acquisition to e...

In [9]:
df = df[df['cleaned_text'] != '']
display(df.head())
print(f"New DataFrame shape: {df.shape}")

,doc_id,source,source_type,publish_timestamp,title,raw_text,url,fetch_timestamp,raw_html,cleaned_text
0,a5be497f1c586e6269c0609e6fb1f591d5afc3e5790743...,PYMNTS,news,2026-03-11T08:02:09+00:00,AI Forensics Takes Aim at Compliance Gridlock,AI Forensics Takes Aim at Compliance Gridlock ...,https://www.pymnts.com/news/artificial-intelli...,2026-03-11T09:01:44.489463+00:00,https://www.pymnts.com/news/artificial-intelli...,ai forensics takes aim at compliance gridlock ...
1,dd8ca37af85b6c3b9a9aa93cc6b381769dfe69e767e7b1...,PYMNTS,news,2026-03-11T08:00:40+00:00,47% of Merchants Report False Declines Cost Th...,47% of Merchants Report False Declines Cost Th...,https://www.pymnts.com/fraud-prevention/2026/4...,2026-03-11T09:01:44.489463+00:00,https://www.pymnts.com/fraud-prevention/2026/4...,of merchants report false declines cost them s...
2,1e1107dd8d70e1b2b4354cfb1a03f2fb89ef02cb846b38...,PYMNTS,news,2026-02-27T22:43:31+00:00,Morgan Stanley Wants to Build the Back Office ...,Morgan Stanley Wants to Build the Back Office ...,https://www.pymnts.com/cryptocurrency/2026/mor...,2026-03-02T09:01:44.601819+00:00,https://www.pymnts.com/cryptocurrency/2026/mor...,morgan stanley wants to build the back office ...
3,a2b322624c7eefbba1f180f64ad12964870b5ea570aaf7...,PYMNTS,news,2026-03-01T21:30:54+00:00,Apple Set to Announce AI-Native Hardware to Un...,Apple Set to Announce AI-Native Hardware to Un...,https://www.pymnts.com/apple/2026/apple-plans-...,2026-03-02T14:01:51.078611+00:00,https://www.pymnts.com/apple/2026/apple-plans-...,apple set to announce ainative hardware to unl...
4,5e22f48845e7bac3e621e6fb1b0467eeecdacf9cff2a97...,PYMNTS,news,2026-02-28T01:19:27+00:00,Visa Closes Prisma and Newpay Acquisition to E...,Visa Closes Prisma and Newpay Acquisition to E...,https://www.pymnts.com/acquisitions/2026/visa-...,2026-03-02T14:01:51.078611+00:00,https://www.pymnts.com/acquisitions/2026/visa-...,visa closes prisma and newpay acquisition to e...

New DataFrame shape: (937, 10)

In [10]:
import pandas as pd

response = supabase.table('article_embeddings').select('*').execute()
data = response.data

# Convert the data to a pandas DataFrame for easier analysis
df_embeddings = pd.DataFrame(data)

# Display the first few rows of the DataFrame
display(df_embeddings.head())

,doc_id,embedding
0,8487fd697ff475b1a091bb76363ebc1d3e2a85a0fe9fe4...,"[-0.022519987,0.008534471,0.0024342104,-0.0774..."
1,153b2bcd4e56eaeea44e21707350e57f11f7cc31c65f13...,"[-0.019306047,-0.007728079,0.0050274194,-0.098..."
2,b0740c5d37de5c16ec0a41d23da60ab63182bfb7bc6c38...,"[0.010557397,-0.02541498,0.012857537,-0.084268..."
3,a8fc4a6d61bac1f07d51f553cea99a2ec4c76e18d2c52d...,"[-0.010596467,-0.0018687332,-0.02154797,-0.082..."
4,eef58c4e44d4d86a7de4c8d3afe6e73d2d3b534fe99228...,"[-0.02412212,0.0025905117,-0.0048901914,-0.078..."

In [11]:
print(df_embeddings.columns.tolist())

['doc_id', 'embedding']

In [12]:
df_embeddings.shape

(937, 2)

In [13]:
import pandas as pd
import google.generativeai as genai
import os


for var in ['HTTP_PROXY', 'HTTPS_PROXY', 'http_proxy', 'https_proxy']:
    os.environ.pop(var, None)

# Configure with an explicit endpoint to bypass local network redirects
genai.configure(
    api_key=GEMINI_API_KEY,
    client_options={'api_endpoint': 'generativelanguage.googleapis.com'}
)

df['doc_id'] = df['doc_id'].astype(str)
df_embeddings['doc_id'] = df_embeddings['doc_id'].astype(str)

if 'embedding' in df.columns:
    df.drop(columns=['embedding'], inplace=True)

# Merge
df = df.merge(df_embeddings[['doc_id', 'embedding']], on='doc_id', how='left')

missing_mask = df['embedding'].isna()
indices_to_embed = df[missing_mask].index

if not indices_to_embed.empty:
    print(f"Generating embeddings for {len(indices_to_embed)} new documents...")

    # Process in batches of 50
    BATCH_SIZE = 50

    for i in range(0, len(indices_to_embed), BATCH_SIZE):
        batch_indices = indices_to_embed[i : i + BATCH_SIZE]
        batch_texts = df.loc[batch_indices, 'cleaned_text'].tolist()

        try:
            response = genai.embed_content(
                model="models/gemini-embedding-001",
                content=batch_texts,
                task_type="retrieval_document"
            )


            embeddings_list = response['embedding']


            df.loc[batch_indices, 'embedding'] = pd.Series(embeddings_list, index=batch_indices)

            print(f"Success: Processed up to row {i + len(batch_texts)}")

        except Exception as e:
            print(f"Error at index {i}: {e}")

else:
    print("All documents already have embeddings.")

print(f"Total rows: {len(df)}")
print(f"Rows with embeddings: {df['embedding'].notna().sum()}")

All documents already have embeddings.
Total rows: 937
Rows with embeddings: 937

In [14]:
import numpy as np

# 1. Clean the data (Crucial: Supabase needs standard Python lists, not Numpy arrays)
df_new_ready = df[df['embedding'].notna()][['doc_id', 'embedding']].copy()
df_new_ready['embedding'] = df_new_ready['embedding'].apply(
    lambda x: x.tolist() if isinstance(x, np.ndarray) else x
)

# 2. Convert to list of dicts
data_to_upsert = df_new_ready.to_dict(orient='records')

# 3. Upsert in smaller chunks to avoid Database Timeout
CHUNK_SIZE = 50
print(f"Upserting {len(data_to_upsert)} rows in chunks of {CHUNK_SIZE}...")

for i in range(0, len(data_to_upsert), CHUNK_SIZE):
    chunk = data_to_upsert[i : i + CHUNK_SIZE]
    try:
        supabase.table("article_embeddings").upsert(
            chunk,
            on_conflict="doc_id"
        ).execute()
        print(f"Successfully upserted chunk {i//CHUNK_SIZE + 1} ({min(i + CHUNK_SIZE, len(data_to_upsert))} rows total)")
    except Exception as e:
        print(f"Failed at chunk starting at index {i}: {e}")

Upserting 937 rows in chunks of 50...
Successfully upserted chunk 1 (50 rows total)
Successfully upserted chunk 2 (100 rows total)
Successfully upserted chunk 3 (150 rows total)
Successfully upserted chunk 4 (200 rows total)
Successfully upserted chunk 5 (250 rows total)
Successfully upserted chunk 6 (300 rows total)
Successfully upserted chunk 7 (350 rows total)
Successfully upserted chunk 8 (400 rows total)
Successfully upserted chunk 9 (450 rows total)
Successfully upserted chunk 10 (500 rows total)
Successfully upserted chunk 11 (550 rows total)
Successfully upserted chunk 12 (600 rows total)
Successfully upserted chunk 13 (650 rows total)
Successfully upserted chunk 14 (700 rows total)
Successfully upserted chunk 15 (750 rows total)
Successfully upserted chunk 16 (800 rows total)
Successfully upserted chunk 17 (850 rows total)
Successfully upserted chunk 18 (900 rows total)
Successfully upserted chunk 19 (937 rows total)

In [15]:
import numpy as np
import google.generativeai as genai

# Define the get_gemini_embeddings function
def get_gemini_embeddings(text):
    try:
        # Ensure text is a list, as embed_content can take a list of strings
        if isinstance(text, str):
            text = [text]

        response = genai.embed_content(
            model="models/gemini-embedding-001",
            content=text,
            task_type="retrieval_document" # Or "retrieval_query" depending on use case
        )
        # For a single text input, return the first embedding
        return response['embedding'][0]
    except Exception as e:
        print(f"Error generating embedding for text: {text}. Error: {e}")
        return None

fraud_concepts = [
    "financial fraud",
    "identity theft",
    "phishing scam",
    "money laundering",
    "cybercrime",
    "account takeover"
]

# Apply get_gemini_embeddings to each concept and convert to NumPy array
fraud_embeddings_list = [get_gemini_embeddings(concept) for concept in fraud_concepts]

# Filter out any None values if embedding generation failed for some concepts
fraud_embeddings_list = [emb for emb in fraud_embeddings_list if emb is not None]

# Only proceed if there are valid embeddings
if fraud_embeddings_list:
    fraud_embeddings_array = np.array(fraud_embeddings_list)

    # Calculate the mean across the rows (axis=0) to get a single fraud_embedding vector
    fraud_embedding = fraud_embeddings_array.mean(axis=0)

    print("Fraud embedding calculated successfully.")
else:
    print("No fraud embeddings could be generated.")

Fraud embedding calculated successfully.

In [16]:
print(f"Shape of fraud_embedding: {fraud_embedding.shape}")

Shape of fraud_embedding: (3072,)

In [17]:
import numpy as np
import ast # Required for safely evaluating string literals

# Function to safely parse an embedding value into a list of floats
def parse_embedding_to_list(embed_value):
    if isinstance(embed_value, str):
        try:
            # Use ast.literal_eval to safely convert string to Python literal (list, tuple, etc.)
            parsed = ast.literal_eval(embed_value)
            if isinstance(parsed, (list, tuple)):
                return [float(x) for x in parsed] # Ensure elements are floats
        except (ValueError, SyntaxError):
            return None # Not a valid string representation of a list
    elif isinstance(embed_value, np.ndarray):
        return embed_value.tolist()
    elif isinstance(embed_value, list):
        # Ensure it's a list of floats
        return [float(x) for x in embed_value]
    return None # For any other unexpected types or None values

# Apply the conversion to the 'embedding' column of the DataFrame
df['embedding'] = df['embedding'].apply(parse_embedding_to_list)

# Filter out any rows where the embedding could not be properly parsed or resulted in None
# This ensures that all elements in the list passed to np.array are valid lists of floats
valid_embeddings_list = [embed for embed in df['embedding'] if embed is not None and isinstance(embed, list)]

# Check for consistency in embedding dimensions before creating the NumPy array
if valid_embeddings_list:
    first_embedding_length = len(valid_embeddings_list[0])
    # Ensure all embeddings have the same dimension
    if not all(len(embed) == first_embedding_length for embed in valid_embeddings_list):
        print("Warning: Some embeddings have inconsistent lengths after cleaning. Proceeding with available consistent ones.")
        # Further filter to only include embeddings of the most common length, or raise an error.
        # For now, we will create the array from the cleaned list, which should be consistent if generation was.

    text_embedding_array = np.array(valid_embeddings_list)
    print(f"Shape of text_embedding_array: {text_embedding_array.shape}")
else:
    print("Warning: No valid embeddings found after cleaning. 'text_embedding_array' will be an empty array.")
    text_embedding_array = np.array([]) # Create an empty array if no valid embeddings

Shape of text_embedding_array: (937, 3072)

In [18]:
fraud_embedding_2d = fraud_embedding.reshape(1, -1)
print(f"Shape of fraud_embedding_2d: {fraud_embedding_2d.shape}")

Shape of fraud_embedding_2d: (1, 3072)

In [19]:
from sklearn.metrics.pairwise import cosine_similarity

similarity_scores = cosine_similarity(text_embedding_array, fraud_embedding_2d)
df['fraud_similarity'] = similarity_scores.flatten()
display(df.head())

,doc_id,source,source_type,publish_timestamp,title,raw_text,url,fetch_timestamp,raw_html,cleaned_text,embedding,fraud_similarity
0,a5be497f1c586e6269c0609e6fb1f591d5afc3e5790743...,PYMNTS,news,2026-03-11T08:02:09+00:00,AI Forensics Takes Aim at Compliance Gridlock,AI Forensics Takes Aim at Compliance Gridlock ...,https://www.pymnts.com/news/artificial-intelli...,2026-03-11T09:01:44.489463+00:00,https://www.pymnts.com/news/artificial-intelli...,ai forensics takes aim at compliance gridlock ...,"[-0.0043854048, 0.0010701711, -0.0039067385, -...",0.675931
1,dd8ca37af85b6c3b9a9aa93cc6b381769dfe69e767e7b1...,PYMNTS,news,2026-03-11T08:00:40+00:00,47% of Merchants Report False Declines Cost Th...,47% of Merchants Report False Declines Cost Th...,https://www.pymnts.com/fraud-prevention/2026/4...,2026-03-11T09:01:44.489463+00:00,https://www.pymnts.com/fraud-prevention/2026/4...,of merchants report false declines cost them s...,"[-0.0027470347, -0.0020576008, -0.0079495255, ...",0.665378
2,1e1107dd8d70e1b2b4354cfb1a03f2fb89ef02cb846b38...,PYMNTS,news,2026-02-27T22:43:31+00:00,Morgan Stanley Wants to Build the Back Office ...,Morgan Stanley Wants to Build the Back Office ...,https://www.pymnts.com/cryptocurrency/2026/mor...,2026-03-02T09:01:44.601819+00:00,https://www.pymnts.com/cryptocurrency/2026/mor...,morgan stanley wants to build the back office ...,"[-0.0075529283, 0.0013231395, 0.015731838, -0....",0.638481
3,a2b322624c7eefbba1f180f64ad12964870b5ea570aaf7...,PYMNTS,news,2026-03-01T21:30:54+00:00,Apple Set to Announce AI-Native Hardware to Un...,Apple Set to Announce AI-Native Hardware to Un...,https://www.pymnts.com/apple/2026/apple-plans-...,2026-03-02T14:01:51.078611+00:00,https://www.pymnts.com/apple/2026/apple-plans-...,apple set to announce ainative hardware to unl...,"[-0.022269502, -0.013018766, 0.00497304, -0.08...",0.597630
4,5e22f48845e7bac3e621e6fb1b0467eeecdacf9cff2a97...,PYMNTS,news,2026-02-28T01:19:27+00:00,Visa Closes Prisma and Newpay Acquisition to E...,Visa Closes Prisma and Newpay Acquisition to E...,https://www.pymnts.com/acquisitions/2026/visa-...,2026-03-02T14:01:51.078611+00:00,https://www.pymnts.com/acquisitions/2026/visa-...,visa closes prisma and newpay acquisition to e...,"[-0.013000765, -0.013009047, -0.021180179, -0....",0.622416

In [20]:
filtered_df = df[df['fraud_similarity'] > 0.4]

display(filtered_df.head())
print(f"Shape of filtered_df: {filtered_df.shape}")

,doc_id,source,source_type,publish_timestamp,title,raw_text,url,fetch_timestamp,raw_html,cleaned_text,embedding,fraud_similarity
0,a5be497f1c586e6269c0609e6fb1f591d5afc3e5790743...,PYMNTS,news,2026-03-11T08:02:09+00:00,AI Forensics Takes Aim at Compliance Gridlock,AI Forensics Takes Aim at Compliance Gridlock ...,https://www.pymnts.com/news/artificial-intelli...,2026-03-11T09:01:44.489463+00:00,https://www.pymnts.com/news/artificial-intelli...,ai forensics takes aim at compliance gridlock ...,"[-0.0043854048, 0.0010701711, -0.0039067385, -...",0.675931
1,dd8ca37af85b6c3b9a9aa93cc6b381769dfe69e767e7b1...,PYMNTS,news,2026-03-11T08:00:40+00:00,47% of Merchants Report False Declines Cost Th...,47% of Merchants Report False Declines Cost Th...,https://www.pymnts.com/fraud-prevention/2026/4...,2026-03-11T09:01:44.489463+00:00,https://www.pymnts.com/fraud-prevention/2026/4...,of merchants report false declines cost them s...,"[-0.0027470347, -0.0020576008, -0.0079495255, ...",0.665378
2,1e1107dd8d70e1b2b4354cfb1a03f2fb89ef02cb846b38...,PYMNTS,news,2026-02-27T22:43:31+00:00,Morgan Stanley Wants to Build the Back Office ...,Morgan Stanley Wants to Build the Back Office ...,https://www.pymnts.com/cryptocurrency/2026/mor...,2026-03-02T09:01:44.601819+00:00,https://www.pymnts.com/cryptocurrency/2026/mor...,morgan stanley wants to build the back office ...,"[-0.0075529283, 0.0013231395, 0.015731838, -0....",0.638481
3,a2b322624c7eefbba1f180f64ad12964870b5ea570aaf7...,PYMNTS,news,2026-03-01T21:30:54+00:00,Apple Set to Announce AI-Native Hardware to Un...,Apple Set to Announce AI-Native Hardware to Un...,https://www.pymnts.com/apple/2026/apple-plans-...,2026-03-02T14:01:51.078611+00:00,https://www.pymnts.com/apple/2026/apple-plans-...,apple set to announce ainative hardware to unl...,"[-0.022269502, -0.013018766, 0.00497304, -0.08...",0.597630
4,5e22f48845e7bac3e621e6fb1b0467eeecdacf9cff2a97...,PYMNTS,news,2026-02-28T01:19:27+00:00,Visa Closes Prisma and Newpay Acquisition to E...,Visa Closes Prisma and Newpay Acquisition to E...,https://www.pymnts.com/acquisitions/2026/visa-...,2026-03-02T14:01:51.078611+00:00,https://www.pymnts.com/acquisitions/2026/visa-...,visa closes prisma and newpay acquisition to e...,"[-0.013000765, -0.013009047, -0.021180179, -0....",0.622416

Shape of filtered_df: (937, 12)

# BERT

In [21]:
import pandas as pd

response = supabase.table('article_analysis').select('*').execute()
data = response.data

# Convert the data to a pandas DataFrame for easier analysis
df_bert_embeddings = pd.DataFrame(data)

# Display the first few rows of the DataFrame
display(df_bert_embeddings.head())

,doc_id,bert_embeddings,cluster_id,age_days,growth,drift,acceleration,stage,risk_score
0,9f626513a0c0cac2594f92f3d88ccee4e32e25192ff4ae...,"[-0.5445262,-0.43997094,-0.965832,0.67447853,0...",80,NaN,NaN,NaN,NaN,None,NaN
1,3a31b34f3978a438ac3895a2e7c18c4b0c31218b32b18d...,"[-0.6583602,-0.5905995,-0.98503256,0.42857268,...",85,NaN,NaN,NaN,NaN,None,NaN
2,377a7997bffa6d5fbba4578421beceea4bb9e53a84331e...,"[-0.8074999,-0.5081343,-0.9670517,0.82887083,0...",45,NaN,NaN,NaN,NaN,None,NaN
3,c133d9dc6b81b6b49e085dab2b81eda2caa3522e2a092c...,"[-0.25792024,0.13084225,0.5253779,-0.1414027,-...",34,NaN,NaN,NaN,NaN,None,NaN
4,9df7207588b77abd223a8780b6ed5adb75ca07413b7819...,"[-0.7585357,-0.36630073,-0.9403099,0.7370016,0...",24,NaN,NaN,NaN,NaN,None,NaN

In [22]:
df_bert_embeddings.shape

(911, 9)

In [23]:
!pip install tf-keras
!pip install transformers==4.42.0

Requirement already satisfied: tf-keras in /usr/local/lib/python3.12/dist-packages (2.19.0)
Requirement already satisfied: tensorflow<2.20,>=2.19 in /usr/local/lib/python3.12/dist-packages (from tf-keras) (2.19.0)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.20,>=2.19->tf-keras) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.20,>=2.19->tf-keras) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.20,>=2.19->tf-keras) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.20,>=2.19->tf-keras) (0.7.0)
Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.20,>=2.19->tf-keras) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.20,>=2.19->tf-keras) (18.1.1)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.20,>=2.19->tf-keras) (3.4.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.20,>=2.19->tf-keras) (26.0)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.20,>=2.19->tf-keras) (5.29.6)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.20,>=2.19->tf-keras) (2.32.4)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.20,>=2.19->tf-keras) (75.2.0)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.20,>=2.19->tf-keras) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.20,>=2.19->tf-keras) (3.3.0)
Requirement already satisfied: typing-extensions>=3.6.6 in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.20,>=2.19->tf-keras) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.20,>=2.19->tf-keras) (2.1.2)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.20,>=2.19->tf-keras) (1.80.0)
Requirement already satisfied: tensorboard~=2.19.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.20,>=2.19->tf-keras) (2.19.0)
Requirement already satisfied: keras>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.20,>=2.19->tf-keras) (3.13.2)
Requirement already satisfied: numpy<2.2.0,>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.20,>=2.19->tf-keras) (1.26.4)
Requirement already satisfied: h5py>=3.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.20,>=2.19->tf-keras) (3.16.0)
Requirement already satisfied: ml-dtypes<1.0.0,>=0.5.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.20,>=2.19->tf-keras) (0.5.4)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from astunparse>=1.6.0->tensorflow<2.20,>=2.19->tf-keras) (0.46.3)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow<2.20,>=2.19->tf-keras) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow<2.20,>=2.19->tf-keras) (0.1.0)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow<2.20,>=2.19->tf-keras) (0.19.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow<2.20,>=2.19->tf-keras) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow<2.20,>=2.19->tf-keras) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow<2.20,>=2.19->tf-keras) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow<2.20,>=2.19->tf-keras) (2026.2.25)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow<2.20,>=2.19->tf-keras) (3.10.2)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow<2.20,>=2.19->tf-keras) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow<2.20,>=2.19->tf-keras) (3.1.7)
Requirement already satisfied: markupsafe>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from werkzeug>=1.0.1->tensorboard~=2.19.0->tensorflow<2.20,>=2.19->tf-keras) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.5.0->tensorflow<2.20,>=2.19->tf-keras) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.5.0->tensorflow<2.20,>=2.19->tf-keras) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras>=3.5.0->tensorflow<2.20,>=2.19->tf-keras) (0.1.2)
Requirement already satisfied: transformers==4.42.0 in /usr/local/lib/python3.12/dist-packages (4.42.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers==4.42.0) (3.25.2)
Requirement already satisfied: huggingface-hub<1.0,>=0.23.2 in /usr/local/lib/python3.12/dist-packages (from transformers==4.42.0) (0.36.2)
Requirement already satisfied: numpy<2.0,>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers==4.42.0) (1.26.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers==4.42.0) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers==4.42.0) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers==4.42.0) (2025.11.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from transformers==4.42.0) (2.32.4)
Requirement already satisfied: tokenizers<0.20,>=0.19 in /usr/local/lib/python3.12/dist-packages (from transformers==4.42.0) (0.19.1)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.12/dist-packages (from transformers==4.42.0) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers==4.42.0) (4.67.3)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.23.2->transformers==4.42.0) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.23.2->transformers==4.42.0) (1.4.2)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.23.2->transformers==4.42.0) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.42.0) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.42.0) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.42.0) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.42.0) (2026.2.25)

In [24]:
import tf_keras
print(tf_keras.__version__)

2.19.0

In [25]:
import numpy as np
import pandas as pd
import tensorflow as tf
import transformers

In [26]:
max_length = 128  # Maximum length of input sentence to the model.
batch_size = 32
epochs = 2

In [27]:
class BertInputBatchGenerator(tf_keras.utils.Sequence):

    def __init__(
        self,
        sentence_pairs,
        labels,
        batch_size=batch_size,
        shuffle=True,
        include_targets=True,
    ):
        self.sentence_pairs = sentence_pairs
        self.labels = labels
        self.shuffle = shuffle
        self.batch_size = batch_size
        self.include_targets = include_targets
        # Load our BERT Tokenizer to encode the text.
        # We will use bert-base-uncased pretrained model.
        self.tokenizer = transformers.BertTokenizer.from_pretrained(
            "bert-base-uncased", do_lower_case=True
        )
        self.indexes = np.arange(len(self.sentence_pairs))
        self.on_epoch_end()

    def __len__(self):
        # Return the number of batches per epoch.
        return len(self.sentence_pairs) // self.batch_size

    def __getitem__(self, idx):
        # Retrieves the batch of index.
        indexes = self.indexes[idx * self.batch_size : (idx + 1) * self.batch_size]
        sentence_pairs = self.sentence_pairs[indexes]

        # With BERT tokenizer's batch_encode_plus, batch of both the sentences are
        # encoded together and separated by [SEP] token.
        encoded = self.tokenizer.batch_encode_plus(
            sentence_pairs.tolist(),
            add_special_tokens=True,
            max_length=max_length,
            return_attention_mask=True,
            return_token_type_ids=True,
            padding='max_length', # Changed from pad_to_max_length=True
            truncation=True, # Added truncation=True
            return_tensors="tf",
        )

        # Convert batch of encoded features to numpy array.
        input_ids = np.array(encoded["input_ids"], dtype="int32")
        attention_masks = np.array(encoded["attention_mask"], dtype="int32")
        token_type_ids = np.array(encoded["token_type_ids"], dtype="int32")

        # Set to true if the data generator is used for training/validation.
        if self.include_targets:
            labels = np.array(self.labels[indexes], dtype="int32")
            return [input_ids, attention_masks, token_type_ids], labels
        else:
            return [input_ids, attention_masks, token_type_ids]

    def on_epoch_end(self):
        # Shuffle indexes after each epoch if shuffle is set to True.
        if self.shuffle:
            np.random.RandomState(42).shuffle(self.indexes)

In [28]:
strategy = tf.distribute.MirroredStrategy()

with strategy.scope():
    # Encoded token ids from BERT tokenizer.
    input_ids = tf_keras.Input(
        shape=(max_length,), dtype=tf.int32, name="input_ids"
    )
    # Attention masks indicate which tokens are real and which are fake (padding).
    attention_masks = tf_keras.Input(
        shape=(max_length,), dtype=tf.int32, name="attention_masks"
    )
    # Token type ids indicate which tokens belong to Sentence 1 and which to Sentence 2.
    token_type_ids = tf_keras.Input(
        shape=(max_length,), dtype=tf.int32, name="token_type_ids"
    )
    # Loading pretrained BERT model.
    bert_model = transformers.TFBertModel.from_pretrained("bert-base-uncased")
    # Freeze the BERT model to reuse the pretrained features without modifying them.
    bert_model.trainable = False

    # Explicit conversion of KerasTensors to tf.Tensors
    bert_output = bert_model.bert(
        input_ids, attention_mask=attention_masks, token_type_ids=token_type_ids
    )
    sequence_output = bert_output.last_hidden_state
    pooled_output = bert_output.pooler_output

    # Add trainable layers on top of frozen layers to adapt the pretrained features on the new data.
    bi_lstm = tf_keras.layers.Bidirectional(
        tf_keras.layers.LSTM(64, return_sequences=True)
    )(sequence_output)
    # Applying hybrid pooling approach to bi_lstm sequence output.
    avg_pool = tf_keras.layers.GlobalAveragePooling1D()(bi_lstm)
    dropout = tf_keras.layers.Dropout(0.3)(avg_pool)
    output = tf_keras.layers.Dense(3, activation="softmax")(dropout)


    model = tf_keras.Model(
        inputs=[input_ids, attention_masks, token_type_ids], outputs=output
    )

    model.compile(
        optimizer=tf_keras.optimizers.Adam(),
        loss="categorical_crossentropy",
        metrics=["acc"],
    )


print(f"Strategy: {strategy}")
model.summary()

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFBertModel: ['cls.predictions.bias', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.dense.weight', 'cls.seq_relationship.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.LayerNorm.bias']
- This IS expected if you are initializing TFBertModel from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
All the weights of TFBertModel were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions without further training.

Strategy: <tensorflow.python.distribute.mirrored_strategy.MirroredStrategy object at 0x7c7d20973800>
Model: "model"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to
==================================================================================================
 input_ids (InputLayer)      [(None, 128)]                0         []

 attention_masks (InputLaye  [(None, 128)]                0         []
 r)

 token_type_ids (InputLayer  [(None, 128)]                0         []
 )

 bert (TFBertMainLayer)      TFBaseModelOutputWithPooli   1094822   ['input_ids[0][0]',
                             ngAndCrossAttentions(last_   40         'attention_masks[0][0]',
                             hidden_state=(None, 128, 7              'token_type_ids[0][0]']
                             68),
                              pooler_output=(None, 768)
                             , past_key_values=None, hi
                             dden_states=None, attentio
                             ns=None, cross_attentions=
                             None)

 bidirectional (Bidirection  (None, 128, 128)             426496    ['bert[0][0]']
 al)

 global_average_pooling1d (  (None, 128)                  0         ['bidirectional[0][0]']
 GlobalAveragePooling1D)

 dropout_37 (Dropout)        (None, 128)                  0         ['global_average_pooling1d[0][
                                                                    0]']

 dense (Dense)               (None, 3)                    387       ['dropout_37[0][0]']

==================================================================================================
Total params: 109909123 (419.27 MB)
Trainable params: 426883 (1.63 MB)
Non-trainable params: 109482240 (417.64 MB)
__________________________________________________________________________________________________

In [29]:
import numpy as np
from tensorflow.keras.utils import to_categorical
from sklearn.model_selection import train_test_split

# Identify IDs that already have embeddings
existing_ids = df_bert_embeddings['doc_id'].unique()

# Filter filtered_df for IDs that are NOT in the existing_ids list
to_process_df = filtered_df[~filtered_df['doc_id'].isin(existing_ids)].copy()

if to_process_df.empty:
    print("All articles already have embeddings. Nothing to do!")
else:
    print(f"New articles to process: {len(to_process_df)}")

    num_classes = 3
    # Use the length of the filtered subset
    new_dummy_labels = np.random.randint(0, num_classes, size=len(to_process_df))

    # This was the missing function
    ohe_labels = to_categorical(new_dummy_labels, num_classes=num_classes)

    # Split the NEW data into training and validation sets
    # Added 'ids_train' and 'ids_val' so you can map embeddings back to doc_ids later
    X_train, X_val, y_train, y_val, ids_train, ids_val = train_test_split(
        to_process_df['cleaned_text'].values,
        ohe_labels,
        to_process_df['doc_id'].values,
        test_size=0.2,
        random_state=42,
        stratify=new_dummy_labels
    )

    # Create generators for the new batch
    # Make sure 'batch_size' is defined (e.g., batch_size = 16 or 32)
    train_data_generator = BertInputBatchGenerator(
        X_train, y_train, batch_size=batch_size, shuffle=True
    )
    valid_data_generator = BertInputBatchGenerator(
        X_val, y_val, batch_size=batch_size, shuffle=False
    )

    print(f"Incremental setup complete for {len(to_process_df)} articles.")

New articles to process: 26

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

Incremental setup complete for 26 articles.

In [30]:
import numpy as np
import transformers

# Initialize the tokenizer globally
tokenizer = transformers.BertTokenizer.from_pretrained(
    "bert-base-uncased", do_lower_case=True
)

# We will directly use to_process_df which contains the new articles identified
if not to_process_df.empty:
    print(f"🛠️ Generating 768-dim BERT features for {len(to_process_df)} new articles...")

    # 2. Tokenize the cleaned text of the new articles
    encoded_new_articles = tokenizer.batch_encode_plus(
        to_process_df['cleaned_text'].fillna("").astype(str).tolist(),
        add_special_tokens=True,
        max_length=max_length,
        padding='max_length',
        truncation=True,
        return_tensors="tf"
    )

    # 3. Model Inference - Get embeddings from the BERT layer
    try:
        # Assuming your base BERT model variable is 'bert_model'
        outputs = bert_model.bert(
            input_ids=encoded_new_articles['input_ids'],
            attention_mask=encoded_new_articles['attention_mask'],
            token_type_ids=encoded_new_articles['token_type_ids']
        )
        raw_vectors = outputs.pooler_output.numpy()
    except Exception as e:
        print(f"Error using bert_model.bert: {e}")
        print("Falling back to model.layers[0] to extract BERT embeddings...")
        # Fallback: Try accessing the first layer of your current 'model'
        bert_layer_output = model.layers[0](
            [encoded_new_articles['input_ids'],
             encoded_new_articles['attention_mask'],
             encoded_new_articles['token_type_ids']]
        )
        raw_vectors = bert_layer_output.pooler_output.numpy()

    # 4. Sanitize and Verify
    sanitized_vectors = np.nan_to_num(raw_vectors, nan=0.0).tolist()

    print(f"✅ Generated {len(sanitized_vectors)} vectors.")
    print(f"📏 New Dimension Check: {len(sanitized_vectors[0])} (Target: 768)")

    # 5. Create a DataFrame for new embeddings
    new_embeddings_df = pd.DataFrame({
        'doc_id': to_process_df['doc_id'].values,
        'bert_embeddings': sanitized_vectors
    })

    # 6. Append new embeddings to df_bert_embeddings
    # Ensure we don't duplicate if for some reason an ID exists but was in to_process_df
    df_bert_embeddings = pd.concat([df_bert_embeddings,
                                    new_embeddings_df[~new_embeddings_df['doc_id'].isin(df_bert_embeddings['doc_id'])]],
                                   ignore_index=True)

    print(f"Updated df_bert_embeddings shape: {df_bert_embeddings.shape}")
else:
    print("No new articles to process for BERT embeddings.")

🛠️ Generating 768-dim BERT features for 26 new articles...
✅ Generated 26 vectors.
📏 New Dimension Check: 768 (Target: 768)
Updated df_bert_embeddings shape: (937, 9)

In [31]:
df_bert_embeddings.shape

(937, 9)

In [32]:
#from sklearn.model_selection import train_test_split
#from tensorflow.keras.utils import to_categorical

#num_classes = 3
#dummy_labels = np.random.randint(0, num_classes, size=len(df))

# One-hot encode the dummy labels as required by categorical_crossentropy
#ohe_labels = to_categorical(dummy_labels, num_classes=num_classes)

# Split the data into training and validation sets
#X_train, X_val, y_train, y_val = train_test_split(
#    filtered_df['cleaned_text'].values,
 #   ohe_labels,
  #  test_size=0.2,
   # random_state=42,
    #stratify=dummy_labels # Stratify based on the original dummy labels
#)

#print(f"Training set size: {len(X_train)} samples")
#print(f"Validation set size: {len(X_val)} samples")
#print(f"Shape of training labels: {y_train.shape}")

# Create data generators for training and validation
#train_data_generator = BertInputBatchGenerator(
 #   X_train, y_train, batch_size=batch_size, shuffle=True
#)
#valid_data_generator = BertInputBatchGenerator(
 #   X_val, y_val, batch_size=batch_size, shuffle=False
#)

#print("BERT data generators for training and validation created.")

In [33]:
#import os

#history = model.fit(
#    train_data_generator,
 #   validation_data=valid_data_generator,
  #  epochs=epochs,
   # use_multiprocessing=True,
    #workers=os.cpu_count()
#)

#print("BERT model training complete.")

In [34]:
#loss, accuracy = model.evaluate(valid_data_generator)
#print(f"Validation Loss: {loss:.4f}")
#print(f"Validation Accuracy: {accuracy:.4f}")

In [35]:
#bert_input_ids = tf.constant(df['input_ids'].tolist(), dtype=tf.int32)
#bert_attention_masks = tf.constant(df['attention_mask'].tolist(), dtype=tf.int32)
#bert_token_type_ids = tf.constant(df['token_type_ids'].tolist(), dtype=tf.int32)

# Use the bert_model.bert() function to process these inputs
#bert_output = bert_model.bert(
 #   bert_input_ids,
  #  attention_mask=bert_attention_masks,
   # token_type_ids=bert_token_type_ids
#)

# Extract the pooled_output from the bert_output
#pooled_output = bert_output.pooler_output

# Convert the pooled_output to a list of NumPy arrays and store it in a new column
#filtered_df['bert_embedding'] = pooled_output.numpy().tolist()

# Display the head of the DataFrame to show the new 'bert_embedding' column
#display(filtered_df.head())
#print("BERT embeddings generated and added to DataFrame.")

In [36]:
import numpy as np
import json
import pandas as pd
import math

# 1. Force sync and SELECT ONLY NECESSARY COLUMNS
# This is the most important change: we drop everything except ID and Vector
df_final = df_bert_embeddings[['doc_id', 'bert_embeddings']].copy()

if 'bert_embeddings' in df_final.columns:
    df_final = df_final.rename(columns={'bert_embeddings': 'bert_embeddings'})

print(f"Starting surgical pipeline: {len(df_final)} rows found.")

# 2. BRUTE FORCE Sanitization (Re-running to be 100% safe)
def final_sanitizer(val):
    vec = None
    if isinstance(val, str):
        try: vec = json.loads(val)
        except: return None
    elif isinstance(val, (list, np.ndarray)):
        vec = list(val)

    if vec and len(vec) == 768:
        # Check every float. If it's NaN/Inf, it MUST become 0.0
        return [float(x) if math.isfinite(float(x)) else 0.0 for x in vec]
    return None

df_final['bert_embeddings'] = df_final['bert_embeddings'].apply(final_sanitizer)

# 3. Validation
df_final = df_final.dropna(subset=['bert_embeddings'])
final_count = len(df_final)
print(f"Validated {final_count} rows.")

# 4. Upsert Execution - strictly doc_id and bert_embeddings
# This creates a list of dicts with ONLY two keys
data_to_upsert = df_final[['doc_id', 'bert_embeddings']].to_dict(orient='records')
CHUNK_SIZE = 50

print(f"Upserting {len(data_to_upsert)} rows to Supabase...")
for i in range(0, len(data_to_upsert), CHUNK_SIZE):
    chunk = data_to_upsert[i : i + CHUNK_SIZE]
    try:
        supabase.table("article_analysis").upsert(
            chunk,
            on_conflict="doc_id"
        ).execute()
        print(f"✅ Progress: {min(i + CHUNK_SIZE, final_count)}/{final_count}")
    except Exception as e:
        print(f"❌ Error at chunk {i}: {e}")
        # If it still fails, the error isn't in the vector.
        # Check the ID itself.
        if i == 0:
             print(f"Sample Row Keys: {chunk[0].keys()}")

print("Database synchronization complete.")

Starting surgical pipeline: 937 rows found.
Validated 937 rows.
Upserting 937 rows to Supabase...
✅ Progress: 50/937
✅ Progress: 100/937
✅ Progress: 150/937
✅ Progress: 200/937
✅ Progress: 250/937
✅ Progress: 300/937
✅ Progress: 350/937
✅ Progress: 400/937
✅ Progress: 450/937
✅ Progress: 500/937
✅ Progress: 550/937
✅ Progress: 600/937
✅ Progress: 650/937
✅ Progress: 700/937
✅ Progress: 750/937
✅ Progress: 800/937
✅ Progress: 850/937
✅ Progress: 900/937
✅ Progress: 937/937
Database synchronization complete.

#Clustering

In [37]:
import numpy as np

# Convert the list of 768-dim vectors into a single 2D NumPy array (909, 768)
embeddings_matrix = np.array(df_final['bert_embeddings'].tolist())

# Final sanity check: ensure no NaNs survived
if np.isnan(embeddings_matrix).any():
    print("⚠️ Found NaNs in matrix. Replacing with 0.0...")
    embeddings_matrix = np.nan_to_num(embeddings_matrix)

print(f"Matrix shape ready for UMAP: {embeddings_matrix.shape}")

Matrix shape ready for UMAP: (937, 768)

In [38]:
import umap
import hdbscan
from sklearn.metrics import silhouette_score

# 1. Compress 768D BERT to 5D UMAP
reducer = umap.UMAP(
    n_neighbors=5,       # CRITICAL: Lowering this forces BERT to find tiny, local groups
    n_components=5,      # Keep 5D to allow for clear density separation
    metric='cosine',
    min_dist=0.0,        # Ensure points overlap as little as possible
    random_state=42
)
u_embeddings = reducer.fit_transform(embeddings_matrix)

# 2. Run HDBSCAN on the COMPRESSED data
clusterer = hdbscan.HDBSCAN(
    min_cluster_size=5,  # Smallest possible valid "topic"
    min_samples=1,       # Don't ignore "borderline" points
    cluster_selection_method='leaf', # Pick the most specific sub-clusters
    metric='euclidean'
)
new_labels = clusterer.fit_predict(u_embeddings)

# 3. Re-calculate Silhouette (excluding noise -1 for a fair test)
mask = new_labels != -1
if mask.any():
    score = silhouette_score(u_embeddings[mask], new_labels[mask])
    print(f"New Silhouette Score: {score:.4f}")
    print(pd.Series(new_labels).value_counts())

/usr/local/lib/python3.12/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

New Silhouette Score: 0.5414
-1     154
 41     26
 3      25
 40     22
 45     19
      ...
 51      5
 78      5
 82      5
 73      5
 79      5
Name: count, Length: 86, dtype: int64

In [39]:
# First, ensure filtered_df has the BERT embeddings from df_final

# Drop any existing bert_embeddings columns that might have accumulated
# from previous runs or merges.
cols_to_drop = [col for col in filtered_df.columns if 'bert_embeddings' in col]
if cols_to_drop:
    filtered_df.drop(columns=cols_to_drop, inplace=True)

# Now perform the merge
filtered_df = pd.merge(filtered_df, df_final[['doc_id', 'bert_embeddings']], on='doc_id', how='left')

# 1. Update your dataframe with the new, higher-quality labels
filtered_df['cluster_id'] = new_labels

# 2. Get the membership probabilities from the UMAP-based run
filtered_df['cluster_density'] = clusterer.probabilities_

In [40]:
print(filtered_df)

                                                doc_id      source  \
0    a5be497f1c586e6269c0609e6fb1f591d5afc3e5790743...      PYMNTS
1    dd8ca37af85b6c3b9a9aa93cc6b381769dfe69e767e7b1...      PYMNTS
2    1e1107dd8d70e1b2b4354cfb1a03f2fb89ef02cb846b38...      PYMNTS
3    a2b322624c7eefbba1f180f64ad12964870b5ea570aaf7...      PYMNTS
4    5e22f48845e7bac3e621e6fb1b0467eeecdacf9cff2a97...      PYMNTS
..                                                 ...         ...
932  fc4eb066a52fc941d955b2f8681d1ad02af5ceb60db538...      PYMNTS
933  8605c0cc60c2218c5723c6632c14b003b23c6b6032db93...  TechCrunch
934  b284054514d88df3b16914551daeef5b516dd85360316d...  TechCrunch
935  bb2d5794be2b0da9e6bc0f56cc0f1ec93c3a890482ddce...  TechCrunch
936  e6016a094e572faeb1c5016236c4747b436e34ebf3c48e...  TechCrunch

    source_type          publish_timestamp  \
0          news  2026-03-11T08:02:09+00:00
1          news  2026-03-11T08:00:40+00:00
2          news  2026-02-27T22:43:31+00:00
3          news  2026-03-01T21:30:54+00:00
4          news  2026-02-28T01:19:27+00:00
..          ...                        ...
932        news  2026-03-31T19:55:38+00:00
933        news  2026-03-19T15:08:31+00:00
934        news  2026-03-19T13:19:41+00:00
935        news  2026-03-18T18:32:32+00:00
936        news  2026-03-18T14:37:15+00:00

                                                 title  \
0        AI Forensics Takes Aim at Compliance Gridlock
1    47% of Merchants Report False Declines Cost Th...
2    Morgan Stanley Wants to Build the Back Office ...
3    Apple Set to Announce AI-Native Hardware to Un...
4    Visa Closes Prisma and Newpay Acquisition to E...
..                                                 ...
932  Visa and Ramp Develop AI Agents for Corporate ...
933  CISA urges companies to secure Microsoft Intun...
934  Consumer-focused privacy company Cloaked raise...
935  FBI is buying location data to track US citize...
936  Marquis says over 672,000 people had personal ...

                                              raw_text  \
0    AI Forensics Takes Aim at Compliance Gridlock ...
1    47% of Merchants Report False Declines Cost Th...
2    Morgan Stanley Wants to Build the Back Office ...
3    Apple Set to Announce AI-Native Hardware to Un...
4    Visa Closes Prisma and Newpay Acquisition to E...
..                                                 ...
932  Visa and Ramp Develop AI Agents for Corporate ...
933  The U.S. Cybersecurity and Infrastructure Secu...
934  Consumer-facing security tools often focus on ...
935  The FBI has resumed purchasing reams of Americ...
936  Marquis, a technology company used by hundreds...

                                                   url  \
0    https://www.pymnts.com/news/artificial-intelli...
1    https://www.pymnts.com/fraud-prevention/2026/4...
2    https://www.pymnts.com/cryptocurrency/2026/mor...
3    https://www.pymnts.com/apple/2026/apple-plans-...
4    https://www.pymnts.com/acquisitions/2026/visa-...
..                                                 ...
932  https://www.pymnts.com/news/b2b-payments/2026/...
933  https://techcrunch.com/2026/03/19/cisa-urges-c...
934  https://techcrunch.com/2026/03/19/consumer-foc...
935  https://techcrunch.com/2026/03/18/fbi-is-buyin...
936  https://techcrunch.com/2026/03/18/marquis-says...

                      fetch_timestamp  \
0    2026-03-11T09:01:44.489463+00:00
1    2026-03-11T09:01:44.489463+00:00
2    2026-03-02T09:01:44.601819+00:00
3    2026-03-02T14:01:51.078611+00:00
4    2026-03-02T14:01:51.078611+00:00
..                                ...
932  2026-04-01T12:11:39.204340+00:00
933  2026-04-01T12:11:46.664683+00:00
934  2026-04-01T12:11:46.664683+00:00
935  2026-04-01T12:11:46.664683+00:00
936  2026-04-01T12:11:46.664683+00:00

                                              raw_html  \
0    https://www.pymnts.com/news/artificial-intelli...
1    https://www.pymnts.com/fraud-prevention/2026/4...
2    https://www.pymnts.com/cryptocurrency/2026/mor...
3    https://www.pymnts.com/apple/2026/apple-plans-...
4    https://www.pymnts.com/acquisitions/2026/visa-...
..                                                 ...
932  https://www.pymnts.com/news/b2b-payments/2026/...
933  https://techcrunch.com/2026/03/19/cisa-urges-c...
934  https://techcrunch.com/2026/03/19/consumer-foc...
935  https://techcrunch.com/2026/03/18/fbi-is-buyin...
936  https://techcrunch.com/2026/03/18/marquis-says...

                                          cleaned_text  \
0    ai forensics takes aim at compliance gridlock ...
1    of merchants report false declines cost them s...
2    morgan stanley wants to build the back office ...
3    apple set to announce ainative hardware to unl...
4    visa closes prisma and newpay acquisition to e...
..                                                 ...
932  visa and ramp develop ai agents for corporate ...
933  the us cybersecurity and infrastructure securi...
934  consumerfacing security tools often focus on o...
935  the fbi has resumed purchasing reams of americ...
936  marquis a technology company used by hundreds ...

                                             embedding  fraud_similarity  \
0    [-0.0043854048, 0.0010701711, -0.0039067385, -...          0.675931
1    [-0.0027470347, -0.0020576008, -0.0079495255, ...          0.665378
2    [-0.0075529283, 0.0013231395, 0.015731838, -0....          0.638481
3    [-0.022269502, -0.013018766, 0.00497304, -0.08...          0.597630
4    [-0.013000765, -0.013009047, -0.021180179, -0....          0.622416
..                                                 ...               ...
932  [-0.02316147, 0.009607655, -0.008070779, -0.08...          0.698807
933  [-0.026284294, 0.026215771, -0.0035232145, -0....          0.754137
934  [-0.027780263, -0.0017263477, -0.00048906385, ...          0.741164
935  [-0.02734466, 0.01286284, 0.002084371, -0.0762...          0.737206
936  [-0.028925685, 0.021759417, -0.024525248, -0.0...          0.766864

                                       bert_embeddings  cluster_id  \
0    [-0.6511983, -0.45307463, -0.84301215, 0.52435...          23
1    [-0.46178085, -0.29034305, -0.88876635, 0.2655...          44
2    [-0.6168637, -0.49527842, -0.97205144, 0.50723...          10
3    [-0.70740056, -0.3899894, -0.8679343, 0.396243...           0
4    [-0.6120617, -0.33784258, -0.8636323, 0.615351...          32
..                                                 ...         ...
932  [-0.60809237, -0.45355684, -0.9640761, 0.66660...          34
933  [-0.76178783, -0.6032487, -0.65867436, 0.58030...          81
934  [-0.45044976, -0.08368997, -0.4472889, 0.37803...          36
935  [-0.6040099, -0.25711894, -0.41456679, 0.39279...           5
936  [-0.7240836, -0.44986618, -0.90598136, 0.54053...          27

     cluster_density
0           1.000000
1           1.000000
2           1.000000
3           1.000000
4           1.000000
..               ...
932         0.594595
933         1.000000
934         0.709454
935         0.566188
936         1.000000

[937 rows x 15 columns]

In [41]:
# Create a lean dataframe for the initial upsert
df_clusters = filtered_df[['doc_id', 'cluster_id']].copy()

# Ensure cluster_id is a standard Python int (Supabase/Postgres requirement)
df_clusters['cluster_id'] = df_clusters['cluster_id'].astype(int)

# Convert to list of dictionaries
data_to_upsert = df_clusters.to_dict(orient='records')

CHUNK_SIZE = 100
print(f"Updating cluster_id for {len(data_to_upsert)} rows...")

for i in range(0, len(data_to_upsert), CHUNK_SIZE):
    chunk = data_to_upsert[i : i + CHUNK_SIZE]
    try:
        supabase.table("article_analysis").upsert(
            chunk,
            on_conflict="doc_id"
        ).execute()
        print(f"✅ Updated chunk {i//CHUNK_SIZE + 1}")
    except Exception as e:
        print(f"❌ Error at index {i}: {e}")

Updating cluster_id for 937 rows...
✅ Updated chunk 1
✅ Updated chunk 2
✅ Updated chunk 3
✅ Updated chunk 4
✅ Updated chunk 5
✅ Updated chunk 6
✅ Updated chunk 7
✅ Updated chunk 8
✅ Updated chunk 9
✅ Updated chunk 10

work on the cluster metrics to add more analysis layers: starting here

In [42]:
# if cluster spikes, potentially an emerging threat
filtered_df['publish_timestamp'] = pd.to_datetime(filtered_df['publish_timestamp'])
filtered_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 937 entries, 0 to 936
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   doc_id             937 non-null    object
 1   source             937 non-null    object
 2   source_type        937 non-null    object
 3   publish_timestamp  906 non-null    datetime64[ns, UTC]
 4   title              937 non-null    object
 5   raw_text           937 non-null    object
 6   url                937 non-null    object
 7   fetch_timestamp    937 non-null    object
 8   raw_html           937 non-null    object
 9   cleaned_text       937 non-null    object
 10  embedding          937 non-null    object
 11  fraud_similarity   937 non-null    float64
 12  bert_embeddings    937 non-null    object
 13  cluster_id         937 non-null    int64
 14  cluster_density    937 non-null    float64
dtypes: datetime64[ns, UTC](1), float64(2), int64(1), object(11)
memory usage: 109.9+ KB

In [43]:
filtered_df['week'] = filtered_df['publish_timestamp'].dt.isocalendar().week
display(filtered_df.head())

,doc_id,source,source_type,publish_timestamp,title,raw_text,url,fetch_timestamp,raw_html,cleaned_text,embedding,fraud_similarity,bert_embeddings,cluster_id,cluster_density,week
0,a5be497f1c586e6269c0609e6fb1f591d5afc3e5790743...,PYMNTS,news,2026-03-11 08:02:09+00:00,AI Forensics Takes Aim at Compliance Gridlock,AI Forensics Takes Aim at Compliance Gridlock ...,https://www.pymnts.com/news/artificial-intelli...,2026-03-11T09:01:44.489463+00:00,https://www.pymnts.com/news/artificial-intelli...,ai forensics takes aim at compliance gridlock ...,"[-0.0043854048, 0.0010701711, -0.0039067385, -...",0.675931,"[-0.6511983, -0.45307463, -0.84301215, 0.52435...",23,1.0,11
1,dd8ca37af85b6c3b9a9aa93cc6b381769dfe69e767e7b1...,PYMNTS,news,2026-03-11 08:00:40+00:00,47% of Merchants Report False Declines Cost Th...,47% of Merchants Report False Declines Cost Th...,https://www.pymnts.com/fraud-prevention/2026/4...,2026-03-11T09:01:44.489463+00:00,https://www.pymnts.com/fraud-prevention/2026/4...,of merchants report false declines cost them s...,"[-0.0027470347, -0.0020576008, -0.0079495255, ...",0.665378,"[-0.46178085, -0.29034305, -0.88876635, 0.2655...",44,1.0,11
2,1e1107dd8d70e1b2b4354cfb1a03f2fb89ef02cb846b38...,PYMNTS,news,2026-02-27 22:43:31+00:00,Morgan Stanley Wants to Build the Back Office ...,Morgan Stanley Wants to Build the Back Office ...,https://www.pymnts.com/cryptocurrency/2026/mor...,2026-03-02T09:01:44.601819+00:00,https://www.pymnts.com/cryptocurrency/2026/mor...,morgan stanley wants to build the back office ...,"[-0.0075529283, 0.0013231395, 0.015731838, -0....",0.638481,"[-0.6168637, -0.49527842, -0.97205144, 0.50723...",10,1.0,9
3,a2b322624c7eefbba1f180f64ad12964870b5ea570aaf7...,PYMNTS,news,2026-03-01 21:30:54+00:00,Apple Set to Announce AI-Native Hardware to Un...,Apple Set to Announce AI-Native Hardware to Un...,https://www.pymnts.com/apple/2026/apple-plans-...,2026-03-02T14:01:51.078611+00:00,https://www.pymnts.com/apple/2026/apple-plans-...,apple set to announce ainative hardware to unl...,"[-0.022269502, -0.013018766, 0.00497304, -0.08...",0.597630,"[-0.70740056, -0.3899894, -0.8679343, 0.396243...",0,1.0,9
4,5e22f48845e7bac3e621e6fb1b0467eeecdacf9cff2a97...,PYMNTS,news,2026-02-28 01:19:27+00:00,Visa Closes Prisma and Newpay Acquisition to E...,Visa Closes Prisma and Newpay Acquisition to E...,https://www.pymnts.com/acquisitions/2026/visa-...,2026-03-02T14:01:51.078611+00:00,https://www.pymnts.com/acquisitions/2026/visa-...,visa closes prisma and newpay acquisition to e...,"[-0.013000765, -0.013009047, -0.021180179, -0....",0.622416,"[-0.6120617, -0.33784258, -0.8636323, 0.615351...",32,1.0,9

In [44]:
cluster_counts_by_week = filtered_df.groupby(['week', 'cluster_id']).size().reset_index(name='count')
display(cluster_counts_by_week)

     week  cluster_id  count
0       8          -1     11
1       8           0      1
2       8           2      1
3       8           3      2
4       8           6      1
..    ...         ...    ...
416    14          75      2
417    14          77      1
418    14          81      1
419    14          83      2
420    14          84      1

[421 rows x 3 columns]

In [45]:
# Create time component that tracks established threat/emerging threat
# Drop rows where 'publish_timestamp' is NaT before creating the 'week' column
# This ensures that the 'week' column is consistently populated with valid Period objects
filtered_df = filtered_df.dropna(subset=['publish_timestamp']).copy()
filtered_df['week'] = filtered_df['publish_timestamp'].dt.to_period('W')

/tmp/ipykernel_9911/2724385559.py:5: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  filtered_df['week'] = filtered_df['publish_timestamp'].dt.to_period('W')

In [46]:
cluster_stats_list = []

for week in sorted(filtered_df['week'].unique()):
    weekly_df = filtered_df[filtered_df['week'] == week]

    for cluster_id in sorted(weekly_df['cluster_id'].unique()):
        # Exclude noise points (cluster_id == -1)
        if cluster_id != -1:
            cluster_df = weekly_df[weekly_df['cluster_id'] == cluster_id]

            number_of_articles = len(cluster_df)

            # Ensure there are articles in the cluster before calculating mean embedding
            if number_of_articles > 0:
                # Convert list of embeddings to a NumPy array for mean calculation
                embeddings_array = np.array(cluster_df['bert_embeddings'].tolist())
                mean_embedding = embeddings_array.mean(axis=0)

                cluster_stats_list.append({
                    "week": week,
                    "cluster_id": cluster_id,
                    "count": number_of_articles,
                    "centroid": mean_embedding.tolist() # Store as list for DataFrame compatibility
                })

# Convert the list of dictionaries to a DataFrame for easier analysis
cluster_stats_df = pd.DataFrame(cluster_stats_list)

print("Cluster statistics calculated and stored in 'cluster_stats_df'.")
display(cluster_stats_df.head())

Cluster statistics calculated and stored in 'cluster_stats_df'.

,week,cluster_id,count,centroid
0,2026-02-16/2026-02-22,0,1,"[-0.6516215, -0.44082326, -0.9402752, 0.546513..."
1,2026-02-16/2026-02-22,2,1,"[-0.6329565, -0.4071322, -0.94449395, 0.580058..."
2,2026-02-16/2026-02-22,3,2,"[-0.6491965500000001, -0.34699337, -0.90302545..."
3,2026-02-16/2026-02-22,6,1,"[-0.7076477, -0.3340457, -0.92505264, 0.605015..."
4,2026-02-16/2026-02-22,8,1,"[-0.76272535, -0.56032246, -0.9520977, 0.50924..."

In [47]:
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

cluster_trends_data = []

for cluster_id in sorted(filtered_df['cluster_id'].unique()):
    if cluster_id == -1: # Skip noise points
        continue

    cluster_data = cluster_stats_df[cluster_stats_df['cluster_id'] == cluster_id].sort_values(by='week')

    # Use .apply() to convert each Period object in the Series to a Timestamp
    cluster_data['week_timestamp'] = cluster_data['week'].apply(lambda x: x.to_timestamp())

    if len(cluster_data) < 2:
        continue

    first_week_timestamp = cluster_data['week_timestamp'].iloc[0]

    prev_count = None
    prev_centroid = None
    prev_growth = None

    for index, row in cluster_data.iterrows():
        current_week = row['week']
        current_week_timestamp = row['week_timestamp']
        current_count = row['count']
        current_centroid = np.array(row['centroid']).reshape(1, -1)

        age_days = (current_week_timestamp - first_week_timestamp).days

        growth = 0.0
        drift = 0.0
        acceleration = 0.0

        if prev_count is not None:
            # Calculate growth
            if prev_count != 0:
                growth = (current_count - prev_count) / prev_count
            else:
                growth = np.inf # Handle division by zero

            # Calculate drift
            drift = 1 - cosine_similarity(current_centroid, prev_centroid)[0][0]

            # Calculate acceleration
            if prev_growth is not None:
                acceleration = growth - prev_growth

            cluster_trends_data.append({
                "week": current_week,
                "cluster_id": cluster_id,
                "age_days": age_days,
                "growth": growth,
                "drift": drift,
                "acceleration": acceleration
            })

        prev_count = current_count
        prev_centroid = current_centroid
        prev_growth = growth

cluster_trends_df = pd.DataFrame(cluster_trends_data)

print("Cluster trends calculated successfully.")
display(cluster_trends_df.head())

Cluster trends calculated successfully.

,week,cluster_id,age_days,growth,drift,acceleration
0,2026-02-23/2026-03-01,0,7,2.000000,0.043466,2.000000
1,2026-03-23/2026-03-29,0,35,-0.666667,0.065255,-2.666667
2,2026-03-30/2026-04-05,0,42,0.000000,0.061758,0.666667
3,2026-03-02/2026-03-08,1,7,0.000000,0.022392,0.000000
4,2026-03-09/2026-03-15,1,14,0.000000,0.030052,0.000000

In [48]:
def classify_stage(age_days, growth, acceleration, drift):

    if growth < -0.2:
        return "declining" # decay detection

    if age_days <= 30:
        if growth > 0.3 or drift > 0.2:
            return "emerging"

    elif 30 < age_days <= 90:
        if growth > 0.1:
            return "trending"

    elif age_days >= 180:
        if acceleration < 0.05:
            return "established"

    return "stable"

In [52]:
cluster_trends_df['stage'] = cluster_trends_df.apply(lambda row: classify_stage(
    row['age_days'],
    row['growth'],
    row['acceleration'],
    row['drift']
), axis=1)

print("Cluster stages classified successfully.")
display(cluster_trends_df.head())

Cluster stages classified successfully.

,week,cluster_id,age_days,growth,drift,acceleration,risk_score,stage
0,2026-02-23/2026-03-01,0,7,2.000000,0.043466,2.000000,1.413040,emerging
1,2026-03-23/2026-03-29,0,35,-0.666667,0.065255,-2.666667,-1.047090,declining
2,2026-03-30/2026-04-05,0,42,0.000000,0.061758,0.666667,0.218527,stable
3,2026-03-02/2026-03-08,1,7,0.000000,0.022392,0.000000,0.006718,stable
4,2026-03-09/2026-03-15,1,14,0.000000,0.030052,0.000000,0.009016,stable

In [53]:
cluster_trends_df['risk_score'] = (
    0.4 * cluster_trends_df['growth'] +
    0.3 * cluster_trends_df['acceleration'] +
    0.3 * cluster_trends_df['drift']
)

print("Risk scores calculated and added to 'cluster_trends_df'.")
display(cluster_trends_df.head())

Risk scores calculated and added to 'cluster_trends_df'.

,week,cluster_id,age_days,growth,drift,acceleration,risk_score,stage
0,2026-02-23/2026-03-01,0,7,2.000000,0.043466,2.000000,1.413040,emerging
1,2026-03-23/2026-03-29,0,35,-0.666667,0.065255,-2.666667,-1.047090,declining
2,2026-03-30/2026-04-05,0,42,0.000000,0.061758,0.666667,0.218527,stable
3,2026-03-02/2026-03-08,1,7,0.000000,0.022392,0.000000,0.006718,stable
4,2026-03-09/2026-03-15,1,14,0.000000,0.030052,0.000000,0.009016,stable

In [54]:
print(cluster_trends_df)

                      week  cluster_id  age_days    growth     drift  \
0    2026-02-23/2026-03-01           0         7  2.000000  0.043466
1    2026-03-23/2026-03-29           0        35 -0.666667  0.065255
2    2026-03-30/2026-04-05           0        42  0.000000  0.061758
3    2026-03-02/2026-03-08           1         7  0.000000  0.022392
4    2026-03-09/2026-03-15           1        14  0.000000  0.030052
..                     ...         ...       ...       ...       ...
324  2026-03-30/2026-04-05          83        42 -0.500000  0.093893
325  2026-02-23/2026-03-01          84         7  0.000000  0.014806
326  2026-03-09/2026-03-15          84        21  3.000000  0.013204
327  2026-03-16/2026-03-22          84        28 -0.750000  0.015272
328  2026-03-30/2026-04-05          84        42  0.000000  0.023928

     acceleration  risk_score      stage
0        2.000000    1.413040   emerging
1       -2.666667   -1.047090  declining
2        0.666667    0.218527     stable
3        0.000000    0.006718     stable
4        0.000000    0.009016     stable
..            ...         ...        ...
324     -3.500000   -1.221832  declining
325      0.000000    0.004442     stable
326      3.000000    2.103961   emerging
327     -3.750000   -1.420418  declining
328      0.750000    0.232178     stable

[329 rows x 8 columns]

In [55]:
print("Distribution of cluster stages:")
print(cluster_trends_df['stage'].value_counts())

Distribution of cluster stages:
stage
stable       122
declining     94
emerging      89
trending      24
Name: count, dtype: int64

In [56]:
print("Descriptive statistics for 'risk_score':")
display(cluster_trends_df['risk_score'].describe())

Descriptive statistics for 'risk_score':

count    329.000000
mean       0.151482
std        0.842317
min       -2.395045
25%       -0.339332
50%        0.014422
75%        0.703130
max        4.208692
Name: risk_score, dtype: float64

In [74]:
article_analysis = pd.merge(
    filtered_df,
    cluster_trends_df[['week', 'cluster_id', 'age_days', 'growth', 'drift', 'acceleration', 'stage', 'risk_score']],
    on=['week', 'cluster_id'],
    how='left'
)

print("Filtered DataFrame combined with cluster trends successfully.")
display(article_analysis.head())

Filtered DataFrame combined with cluster trends successfully.

,doc_id,source,source_type,publish_timestamp,title,raw_text,url,fetch_timestamp,raw_html,cleaned_text,...,bert_embeddings,cluster_id,cluster_density,week,age_days,growth,drift,acceleration,stage,risk_score
0,a5be497f1c586e6269c0609e6fb1f591d5afc3e5790743...,PYMNTS,news,2026-03-11 08:02:09+00:00,AI Forensics Takes Aim at Compliance Gridlock,AI Forensics Takes Aim at Compliance Gridlock ...,https://www.pymnts.com/news/artificial-intelli...,2026-03-11T09:01:44.489463+00:00,https://www.pymnts.com/news/artificial-intelli...,ai forensics takes aim at compliance gridlock ...,...,"[-0.6511983, -0.45307463, -0.84301215, 0.52435...",23,1.0,2026-03-09/2026-03-15,14.0,0.0,0.019369,-1.000000,stable,-0.294189
1,dd8ca37af85b6c3b9a9aa93cc6b381769dfe69e767e7b1...,PYMNTS,news,2026-03-11 08:00:40+00:00,47% of Merchants Report False Declines Cost Th...,47% of Merchants Report False Declines Cost Th...,https://www.pymnts.com/fraud-prevention/2026/4...,2026-03-11T09:01:44.489463+00:00,https://www.pymnts.com/fraud-prevention/2026/4...,of merchants report false declines cost them s...,...,"[-0.46178085, -0.29034305, -0.88876635, 0.2655...",44,1.0,2026-03-09/2026-03-15,21.0,2.0,0.064298,2.666667,emerging,1.619290
2,1e1107dd8d70e1b2b4354cfb1a03f2fb89ef02cb846b38...,PYMNTS,news,2026-02-27 22:43:31+00:00,Morgan Stanley Wants to Build the Back Office ...,Morgan Stanley Wants to Build the Back Office ...,https://www.pymnts.com/cryptocurrency/2026/mor...,2026-03-02T09:01:44.601819+00:00,https://www.pymnts.com/cryptocurrency/2026/mor...,morgan stanley wants to build the back office ...,...,"[-0.6168637, -0.49527842, -0.97205144, 0.50723...",10,1.0,2026-02-23/2026-03-01,NaN,NaN,NaN,NaN,NaN,NaN
3,a2b322624c7eefbba1f180f64ad12964870b5ea570aaf7...,PYMNTS,news,2026-03-01 21:30:54+00:00,Apple Set to Announce AI-Native Hardware to Un...,Apple Set to Announce AI-Native Hardware to Un...,https://www.pymnts.com/apple/2026/apple-plans-...,2026-03-02T14:01:51.078611+00:00,https://www.pymnts.com/apple/2026/apple-plans-...,apple set to announce ainative hardware to unl...,...,"[-0.70740056, -0.3899894, -0.8679343, 0.396243...",0,1.0,2026-02-23/2026-03-01,7.0,2.0,0.043466,2.000000,emerging,1.413040
4,5e22f48845e7bac3e621e6fb1b0467eeecdacf9cff2a97...,PYMNTS,news,2026-02-28 01:19:27+00:00,Visa Closes Prisma and Newpay Acquisition to E...,Visa Closes Prisma and Newpay Acquisition to E...,https://www.pymnts.com/acquisitions/2026/visa-...,2026-03-02T14:01:51.078611+00:00,https://www.pymnts.com/acquisitions/2026/visa-...,visa closes prisma and newpay acquisition to e...,...,"[-0.6120617, -0.33784258, -0.8636323, 0.615351...",32,1.0,2026-02-23/2026-03-01,NaN,NaN,NaN,NaN,NaN,NaN

In [75]:
article_analysis.shape

(906, 22)