<a href="https://colab.research.google.com/github/owilli38/DSBA6390-Fraud-Detection-Emerging-Fraud-Signals-Dashbaord-/blob/main/DSBA6390_Fraud_Detection_BERT_%2B_Embeddings.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install supabase

Requirement already satisfied: supabase in /usr/local/lib/python3.12/dist-packages (2.28.3)
Requirement already satisfied: realtime==2.28.3 in /usr/local/lib/python3.12/dist-packages (from supabase) (2.28.3)
Requirement already satisfied: supabase-functions==2.28.3 in /usr/local/lib/python3.12/dist-packages (from supabase) (2.28.3)
Requirement already satisfied: storage3==2.28.3 in /usr/local/lib/python3.12/dist-packages (from supabase) (2.28.3)
Requirement already satisfied: supabase-auth==2.28.3 in /usr/local/lib/python3.12/dist-packages (from supabase) (2.28.3)
Requirement already satisfied: postgrest==2.28.3 in /usr/local/lib/python3.12/dist-packages (from supabase) (2.28.3)
Requirement already satisfied: httpx<0.29,>=0.26 in /usr/local/lib/python3.12/dist-packages (from supabase) (0.28.1)
Requirement already satisfied: yarl>=1.22.0 in /usr/local/lib/python3.12/dist-packages (from supabase) (1.23.0)
Requirement already satisfied: deprecation>=2.1.0 in /usr/local/lib/python3.12/dist-packages (from postgrest==2.28.3->supabase) (2.1.0)
Requirement already satisfied: pydantic<3.0,>=1.9 in /usr/local/lib/python3.12/dist-packages (from postgrest==2.28.3->supabase) (2.12.3)
Requirement already satisfied: typing-extensions>=4.14.0 in /usr/local/lib/python3.12/dist-packages (from realtime==2.28.3->supabase) (4.15.0)
Requirement already satisfied: websockets<16,>=11 in /usr/local/lib/python3.12/dist-packages (from realtime==2.28.3->supabase) (15.0.1)
Requirement already satisfied: pyiceberg>=0.10.0 in /usr/local/lib/python3.12/dist-packages (from storage3==2.28.3->supabase) (0.11.1)
Requirement already satisfied: pyjwt>=2.10.1 in /usr/local/lib/python3.12/dist-packages (from pyjwt[crypto]>=2.10.1->supabase-auth==2.28.3->supabase) (2.12.1)
Requirement already satisfied: strenum>=0.4.15 in /usr/local/lib/python3.12/dist-packages (from supabase-functions==2.28.3->supabase) (0.4.15)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<0.29,>=0.26->supabase) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<0.29,>=0.26->supabase) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<0.29,>=0.26->supabase) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<0.29,>=0.26->supabase) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<0.29,>=0.26->supabase) (0.16.0)
Requirement already satisfied: multidict>=4.0 in /usr/local/lib/python3.12/dist-packages (from yarl>=1.22.0->supabase) (6.7.1)
Requirement already satisfied: propcache>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from yarl>=1.22.0->supabase) (0.4.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from deprecation>=2.1.0->postgrest==2.28.3->supabase) (26.0)
Requirement already satisfied: h2<5,>=3 in /usr/local/lib/python3.12/dist-packages (from httpx[http2]<0.29,>=0.26->postgrest==2.28.3->supabase) (4.3.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0,>=1.9->postgrest==2.28.3->supabase) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0,>=1.9->postgrest==2.28.3->supabase) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0,>=1.9->postgrest==2.28.3->supabase) (0.4.2)
Requirement already satisfied: mmh3<6.0.0,>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from pyiceberg>=0.10.0->storage3==2.28.3->supabase) (5.2.1)
Requirement already satisfied: requests<3.0.0,>=2.20.0 in /usr/local/lib/python3.12/dist-packages (from pyiceberg>=0.10.0->storage3==2.28.3->supabase) (2.32.4)
Requirement already satisfied: click<9.0.0,>=7.1.1 in /usr/local/lib/python3.12/dist-packages (from pyiceberg>=0.10.0->storage3==2.28.3->supabase) (8.3.1)
Requirement already satisfied: rich<15.0.0,>=10.11.0 in /usr/local/lib/python3.12/dist-packages (from pyiceberg>=0.10.0->storage3==2.28.3->supabase) (13.9.4)
Requirement already satisfied: strictyaml<2.0.0,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from pyiceberg>=0.10.0->storage3==2.28.3->supabase) (1.7.3)
Requirement already satisfied: fsspec>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from pyiceberg>=0.10.0->storage3==2.28.3->supabase) (2025.3.0)
Requirement already satisfied: pyparsing<4.0.0,>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from pyiceberg>=0.10.0->storage3==2.28.3->supabase) (3.3.2)
Requirement already satisfied: tenacity<10.0.0,>=8.2.3 in /usr/local/lib/python3.12/dist-packages (from pyiceberg>=0.10.0->storage3==2.28.3->supabase) (9.1.4)
Requirement already satisfied: pyroaring<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from pyiceberg>=0.10.0->storage3==2.28.3->supabase) (1.0.3)
Requirement already satisfied: cachetools<7.0,>=5.5 in /usr/local/lib/python3.12/dist-packages (from pyiceberg>=0.10.0->storage3==2.28.3->supabase) (6.2.6)
Requirement already satisfied: zstandard<1.0.0,>=0.13.0 in /usr/local/lib/python3.12/dist-packages (from pyiceberg>=0.10.0->storage3==2.28.3->supabase) (0.25.0)
Requirement already satisfied: cryptography>=3.4.0 in /usr/local/lib/python3.12/dist-packages (from pyjwt[crypto]>=2.10.1->supabase-auth==2.28.3->supabase) (43.0.3)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.12/dist-packages (from cryptography>=3.4.0->pyjwt[crypto]>=2.10.1->supabase-auth==2.28.3->supabase) (2.0.0)
Requirement already satisfied: hyperframe<7,>=6.1 in /usr/local/lib/python3.12/dist-packages (from h2<5,>=3->httpx[http2]<0.29,>=0.26->postgrest==2.28.3->supabase) (6.1.0)
Requirement already satisfied: hpack<5,>=4.1 in /usr/local/lib/python3.12/dist-packages (from h2<5,>=3->httpx[http2]<0.29,>=0.26->postgrest==2.28.3->supabase) (4.1.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.20.0->pyiceberg>=0.10.0->storage3==2.28.3->supabase) (3.4.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.20.0->pyiceberg>=0.10.0->storage3==2.28.3->supabase) (2.5.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich<15.0.0,>=10.11.0->pyiceberg>=0.10.0->storage3==2.28.3->supabase) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich<15.0.0,>=10.11.0->pyiceberg>=0.10.0->storage3==2.28.3->supabase) (2.19.2)
Requirement already satisfied: python-dateutil>=2.6.0 in /usr/local/lib/python3.12/dist-packages (from strictyaml<2.0.0,>=1.7.0->pyiceberg>=0.10.0->storage3==2.28.3->supabase) (2.9.0.post0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.12->cryptography>=3.4.0->pyjwt[crypto]>=2.10.1->supabase-auth==2.28.3->supabase) (3.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich<15.0.0,>=10.11.0->pyiceberg>=0.10.0->storage3==2.28.3->supabase) (0.1.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.6.0->strictyaml<2.0.0,>=1.7.0->pyiceberg>=0.10.0->storage3==2.28.3->supabase) (1.17.0)

In [ ]:
from supabase import create_client, Client
from google.colab import userdata

# Retrieve credentials from Colab secrets
SUPABASE_URL = userdata.get('SUPABASE_URL')
SUPABASE_KEY = userdata.get('SUPABASE_KEY')

# Create a Supabase client
supabase: Client = create_client(SUPABASE_URL, SUPABASE_KEY)

print("Supabase client created successfully.")

Supabase client created successfully.

In [ ]:
import pandas as pd

response = supabase.table('articles_v1').select('*').execute()
data = response.data

# Convert the data to a pandas DataFrame for easier analysis
df = pd.DataFrame(data)

# Display the first few rows of the DataFrame
display(df.head())

,doc_id,source,source_type,publish_timestamp,title,raw_text,url,fetch_timestamp,raw_html
0,a5be497f1c586e6269c0609e6fb1f591d5afc3e5790743...,PYMNTS,news,2026-03-11T08:02:09+00:00,AI Forensics Takes Aim at Compliance Gridlock,AI Forensics Takes Aim at Compliance Gridlock ...,https://www.pymnts.com/news/artificial-intelli...,2026-03-11T09:01:44.489463+00:00,https://www.pymnts.com/news/artificial-intelli...
1,dd8ca37af85b6c3b9a9aa93cc6b381769dfe69e767e7b1...,PYMNTS,news,2026-03-11T08:00:40+00:00,47% of Merchants Report False Declines Cost Th...,47% of Merchants Report False Declines Cost Th...,https://www.pymnts.com/fraud-prevention/2026/4...,2026-03-11T09:01:44.489463+00:00,https://www.pymnts.com/fraud-prevention/2026/4...
2,1e1107dd8d70e1b2b4354cfb1a03f2fb89ef02cb846b38...,PYMNTS,news,2026-02-27T22:43:31+00:00,Morgan Stanley Wants to Build the Back Office ...,Morgan Stanley Wants to Build the Back Office ...,https://www.pymnts.com/cryptocurrency/2026/mor...,2026-03-02T09:01:44.601819+00:00,https://www.pymnts.com/cryptocurrency/2026/mor...
3,a2b322624c7eefbba1f180f64ad12964870b5ea570aaf7...,PYMNTS,news,2026-03-01T21:30:54+00:00,Apple Set to Announce AI-Native Hardware to Un...,Apple Set to Announce AI-Native Hardware to Un...,https://www.pymnts.com/apple/2026/apple-plans-...,2026-03-02T14:01:51.078611+00:00,https://www.pymnts.com/apple/2026/apple-plans-...
4,5e22f48845e7bac3e621e6fb1b0467eeecdacf9cff2a97...,PYMNTS,news,2026-02-28T01:19:27+00:00,Visa Closes Prisma and Newpay Acquisition to E...,Visa Closes Prisma and Newpay Acquisition to E...,https://www.pymnts.com/acquisitions/2026/visa-...,2026-03-02T14:01:51.078611+00:00,https://www.pymnts.com/acquisitions/2026/visa-...

In [ ]:
df.shape

(720, 9)

In [ ]:
import google.generativeai as genai
from google.colab import userdata

# Retrieve the Gemini API key from Colab secrets
GEMINI_API_KEY = userdata.get('GEMINI_API_KEY')

# Configure the google.generativeai library
genai.configure(api_key=GEMINI_API_KEY)

print("Gemini API key retrieved and Generative AI library configured.")

Gemini API key retrieved and Generative AI library configured.

/usr/local/lib/python3.12/dist-packages/google/colab/_import_hooks/_hook_injector.py:55: FutureWarning:

All support for the `google.generativeai` package has ended. It will no longer be receiving
updates or bug fixes. Please switch to the `google.genai` package as soon as possible.
See README for more details:

https://github.com/google-gemini/deprecated-generative-ai-python/blob/main/README.md

  loader.exec_module(module)

In [ ]:
import re

def clean_text(text):
    if not isinstance(text, str):
        return ""
    # Convert to lowercase
    text = text.lower()
    # Remove special characters and numbers, keep only letters and spaces
    text = re.sub(r'[^a-z\s]', '', text)
    # Remove extra spaces
    text = re.sub(r'\s+', ' ', text).strip()
    return text

print("Text cleaning function 'clean_text' defined.")

Text cleaning function 'clean_text' defined.

In [ ]:
df['cleaned_text'] = df['raw_text'].apply(clean_text)
display(df.head())

,doc_id,source,source_type,publish_timestamp,title,raw_text,url,fetch_timestamp,raw_html,cleaned_text
0,a5be497f1c586e6269c0609e6fb1f591d5afc3e5790743...,PYMNTS,news,2026-03-11T08:02:09+00:00,AI Forensics Takes Aim at Compliance Gridlock,AI Forensics Takes Aim at Compliance Gridlock ...,https://www.pymnts.com/news/artificial-intelli...,2026-03-11T09:01:44.489463+00:00,https://www.pymnts.com/news/artificial-intelli...,ai forensics takes aim at compliance gridlock ...
1,dd8ca37af85b6c3b9a9aa93cc6b381769dfe69e767e7b1...,PYMNTS,news,2026-03-11T08:00:40+00:00,47% of Merchants Report False Declines Cost Th...,47% of Merchants Report False Declines Cost Th...,https://www.pymnts.com/fraud-prevention/2026/4...,2026-03-11T09:01:44.489463+00:00,https://www.pymnts.com/fraud-prevention/2026/4...,of merchants report false declines cost them s...
2,1e1107dd8d70e1b2b4354cfb1a03f2fb89ef02cb846b38...,PYMNTS,news,2026-02-27T22:43:31+00:00,Morgan Stanley Wants to Build the Back Office ...,Morgan Stanley Wants to Build the Back Office ...,https://www.pymnts.com/cryptocurrency/2026/mor...,2026-03-02T09:01:44.601819+00:00,https://www.pymnts.com/cryptocurrency/2026/mor...,morgan stanley wants to build the back office ...
3,a2b322624c7eefbba1f180f64ad12964870b5ea570aaf7...,PYMNTS,news,2026-03-01T21:30:54+00:00,Apple Set to Announce AI-Native Hardware to Un...,Apple Set to Announce AI-Native Hardware to Un...,https://www.pymnts.com/apple/2026/apple-plans-...,2026-03-02T14:01:51.078611+00:00,https://www.pymnts.com/apple/2026/apple-plans-...,apple set to announce ainative hardware to unl...
4,5e22f48845e7bac3e621e6fb1b0467eeecdacf9cff2a97...,PYMNTS,news,2026-02-28T01:19:27+00:00,Visa Closes Prisma and Newpay Acquisition to E...,Visa Closes Prisma and Newpay Acquisition to E...,https://www.pymnts.com/acquisitions/2026/visa-...,2026-03-02T14:01:51.078611+00:00,https://www.pymnts.com/acquisitions/2026/visa-...,visa closes prisma and newpay acquisition to e...

In [ ]:
df = df[df['cleaned_text'] != '']
display(df.head())
print(f"New DataFrame shape: {df.shape}")

,doc_id,source,source_type,publish_timestamp,title,raw_text,url,fetch_timestamp,raw_html,cleaned_text
0,a5be497f1c586e6269c0609e6fb1f591d5afc3e5790743...,PYMNTS,news,2026-03-11T08:02:09+00:00,AI Forensics Takes Aim at Compliance Gridlock,AI Forensics Takes Aim at Compliance Gridlock ...,https://www.pymnts.com/news/artificial-intelli...,2026-03-11T09:01:44.489463+00:00,https://www.pymnts.com/news/artificial-intelli...,ai forensics takes aim at compliance gridlock ...
1,dd8ca37af85b6c3b9a9aa93cc6b381769dfe69e767e7b1...,PYMNTS,news,2026-03-11T08:00:40+00:00,47% of Merchants Report False Declines Cost Th...,47% of Merchants Report False Declines Cost Th...,https://www.pymnts.com/fraud-prevention/2026/4...,2026-03-11T09:01:44.489463+00:00,https://www.pymnts.com/fraud-prevention/2026/4...,of merchants report false declines cost them s...
2,1e1107dd8d70e1b2b4354cfb1a03f2fb89ef02cb846b38...,PYMNTS,news,2026-02-27T22:43:31+00:00,Morgan Stanley Wants to Build the Back Office ...,Morgan Stanley Wants to Build the Back Office ...,https://www.pymnts.com/cryptocurrency/2026/mor...,2026-03-02T09:01:44.601819+00:00,https://www.pymnts.com/cryptocurrency/2026/mor...,morgan stanley wants to build the back office ...
3,a2b322624c7eefbba1f180f64ad12964870b5ea570aaf7...,PYMNTS,news,2026-03-01T21:30:54+00:00,Apple Set to Announce AI-Native Hardware to Un...,Apple Set to Announce AI-Native Hardware to Un...,https://www.pymnts.com/apple/2026/apple-plans-...,2026-03-02T14:01:51.078611+00:00,https://www.pymnts.com/apple/2026/apple-plans-...,apple set to announce ainative hardware to unl...
4,5e22f48845e7bac3e621e6fb1b0467eeecdacf9cff2a97...,PYMNTS,news,2026-02-28T01:19:27+00:00,Visa Closes Prisma and Newpay Acquisition to E...,Visa Closes Prisma and Newpay Acquisition to E...,https://www.pymnts.com/acquisitions/2026/visa-...,2026-03-02T14:01:51.078611+00:00,https://www.pymnts.com/acquisitions/2026/visa-...,visa closes prisma and newpay acquisition to e...

New DataFrame shape: (720, 10)

In [ ]:
def get_gemini_embeddings(text):
    embedding = genai.embed_content(model='models/gemini-embedding-001',
                                    content=text,
                                    task_type="RETRIEVAL_DOCUMENT")
    return embedding['embedding']

print("Embedding function 'get_gemini_embeddings' defined with updated model.")

Embedding function 'get_gemini_embeddings' defined with updated model.

In [ ]:
df['text_embedding'] = df['cleaned_text'].apply(get_gemini_embeddings)
display(df.head())

,doc_id,source,source_type,publish_timestamp,title,raw_text,url,fetch_timestamp,raw_html,cleaned_text,text_embedding
0,a5be497f1c586e6269c0609e6fb1f591d5afc3e5790743...,PYMNTS,news,2026-03-11T08:02:09+00:00,AI Forensics Takes Aim at Compliance Gridlock,AI Forensics Takes Aim at Compliance Gridlock ...,https://www.pymnts.com/news/artificial-intelli...,2026-03-11T09:01:44.489463+00:00,https://www.pymnts.com/news/artificial-intelli...,ai forensics takes aim at compliance gridlock ...,"[-0.011796092, 0.0015656062, -0.0031555267, -0..."
1,dd8ca37af85b6c3b9a9aa93cc6b381769dfe69e767e7b1...,PYMNTS,news,2026-03-11T08:00:40+00:00,47% of Merchants Report False Declines Cost Th...,47% of Merchants Report False Declines Cost Th...,https://www.pymnts.com/fraud-prevention/2026/4...,2026-03-11T09:01:44.489463+00:00,https://www.pymnts.com/fraud-prevention/2026/4...,of merchants report false declines cost them s...,"[-0.01072105, -0.0031541607, -0.004979989, -0...."
2,1e1107dd8d70e1b2b4354cfb1a03f2fb89ef02cb846b38...,PYMNTS,news,2026-02-27T22:43:31+00:00,Morgan Stanley Wants to Build the Back Office ...,Morgan Stanley Wants to Build the Back Office ...,https://www.pymnts.com/cryptocurrency/2026/mor...,2026-03-02T09:01:44.601819+00:00,https://www.pymnts.com/cryptocurrency/2026/mor...,morgan stanley wants to build the back office ...,"[-0.017383078, 0.0040216837, 0.00556588, -0.09..."
3,a2b322624c7eefbba1f180f64ad12964870b5ea570aaf7...,PYMNTS,news,2026-03-01T21:30:54+00:00,Apple Set to Announce AI-Native Hardware to Un...,Apple Set to Announce AI-Native Hardware to Un...,https://www.pymnts.com/apple/2026/apple-plans-...,2026-03-02T14:01:51.078611+00:00,https://www.pymnts.com/apple/2026/apple-plans-...,apple set to announce ainative hardware to unl...,"[-0.021654325, -0.000538251, 0.005908336, -0.0..."
4,5e22f48845e7bac3e621e6fb1b0467eeecdacf9cff2a97...,PYMNTS,news,2026-02-28T01:19:27+00:00,Visa Closes Prisma and Newpay Acquisition to E...,Visa Closes Prisma and Newpay Acquisition to E...,https://www.pymnts.com/acquisitions/2026/visa-...,2026-03-02T14:01:51.078611+00:00,https://www.pymnts.com/acquisitions/2026/visa-...,visa closes prisma and newpay acquisition to e...,"[-0.021424402, 0.001383504, -0.014503705, -0.0..."

In [ ]:
import numpy as np

fraud_concepts = [
    "financial fraud",
    "identity theft",
    "phishing scam",
    "money laundering",
    "cybercrime",
    "account takeover"
]

# Apply get_gemini_embeddings to each concept and convert to NumPy array
fraud_embeddings_list = [get_gemini_embeddings(concept) for concept in fraud_concepts]
fraud_embeddings_array = np.array(fraud_embeddings_list)

# Calculate the mean across the rows (axis=0) to get a single fraud_embedding vector
fraud_embedding = fraud_embeddings_array.mean(axis=0)

print("Fraud embedding calculated successfully.")

Fraud embedding calculated successfully.

In [ ]:
print(f"Shape of fraud_embedding: {fraud_embedding.shape}")

Shape of fraud_embedding: (3072,)

In [ ]:
text_embedding_array = np.array(df['text_embedding'].tolist())
print(f"Shape of text_embedding_array: {text_embedding_array.shape}")

Shape of text_embedding_array: (720, 3072)

In [ ]:
fraud_embedding_2d = fraud_embedding.reshape(1, -1)
print(f"Shape of fraud_embedding_2d: {fraud_embedding_2d.shape}")

Shape of fraud_embedding_2d: (1, 3072)

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

similarity_scores = cosine_similarity(text_embedding_array, fraud_embedding_2d)
df['fraud_similarity'] = similarity_scores.flatten()
display(df.head())

,doc_id,source,source_type,publish_timestamp,title,raw_text,url,fetch_timestamp,raw_html,cleaned_text,text_embedding,fraud_similarity
0,a5be497f1c586e6269c0609e6fb1f591d5afc3e5790743...,PYMNTS,news,2026-03-11T08:02:09+00:00,AI Forensics Takes Aim at Compliance Gridlock,AI Forensics Takes Aim at Compliance Gridlock ...,https://www.pymnts.com/news/artificial-intelli...,2026-03-11T09:01:44.489463+00:00,https://www.pymnts.com/news/artificial-intelli...,ai forensics takes aim at compliance gridlock ...,"[-0.011796092, 0.0015656062, -0.0031555267, -0...",0.749914
1,dd8ca37af85b6c3b9a9aa93cc6b381769dfe69e767e7b1...,PYMNTS,news,2026-03-11T08:00:40+00:00,47% of Merchants Report False Declines Cost Th...,47% of Merchants Report False Declines Cost Th...,https://www.pymnts.com/fraud-prevention/2026/4...,2026-03-11T09:01:44.489463+00:00,https://www.pymnts.com/fraud-prevention/2026/4...,of merchants report false declines cost them s...,"[-0.01072105, -0.0031541607, -0.004979989, -0....",0.739476
2,1e1107dd8d70e1b2b4354cfb1a03f2fb89ef02cb846b38...,PYMNTS,news,2026-02-27T22:43:31+00:00,Morgan Stanley Wants to Build the Back Office ...,Morgan Stanley Wants to Build the Back Office ...,https://www.pymnts.com/cryptocurrency/2026/mor...,2026-03-02T09:01:44.601819+00:00,https://www.pymnts.com/cryptocurrency/2026/mor...,morgan stanley wants to build the back office ...,"[-0.017383078, 0.0040216837, 0.00556588, -0.09...",0.718336
3,a2b322624c7eefbba1f180f64ad12964870b5ea570aaf7...,PYMNTS,news,2026-03-01T21:30:54+00:00,Apple Set to Announce AI-Native Hardware to Un...,Apple Set to Announce AI-Native Hardware to Un...,https://www.pymnts.com/apple/2026/apple-plans-...,2026-03-02T14:01:51.078611+00:00,https://www.pymnts.com/apple/2026/apple-plans-...,apple set to announce ainative hardware to unl...,"[-0.021654325, -0.000538251, 0.005908336, -0.0...",0.692691
4,5e22f48845e7bac3e621e6fb1b0467eeecdacf9cff2a97...,PYMNTS,news,2026-02-28T01:19:27+00:00,Visa Closes Prisma and Newpay Acquisition to E...,Visa Closes Prisma and Newpay Acquisition to E...,https://www.pymnts.com/acquisitions/2026/visa-...,2026-03-02T14:01:51.078611+00:00,https://www.pymnts.com/acquisitions/2026/visa-...,visa closes prisma and newpay acquisition to e...,"[-0.021424402, 0.001383504, -0.014503705, -0.0...",0.709055

In [ ]:
filtered_df = df[df['fraud_similarity'] > 0.4]

display(filtered_df.head())
print(f"Shape of filtered_df: {filtered_df.shape}")

,doc_id,source,source_type,publish_timestamp,title,raw_text,url,fetch_timestamp,raw_html,cleaned_text,text_embedding,fraud_similarity
0,a5be497f1c586e6269c0609e6fb1f591d5afc3e5790743...,PYMNTS,news,2026-03-11T08:02:09+00:00,AI Forensics Takes Aim at Compliance Gridlock,AI Forensics Takes Aim at Compliance Gridlock ...,https://www.pymnts.com/news/artificial-intelli...,2026-03-11T09:01:44.489463+00:00,https://www.pymnts.com/news/artificial-intelli...,ai forensics takes aim at compliance gridlock ...,"[-0.011796092, 0.0015656062, -0.0031555267, -0...",0.749914
1,dd8ca37af85b6c3b9a9aa93cc6b381769dfe69e767e7b1...,PYMNTS,news,2026-03-11T08:00:40+00:00,47% of Merchants Report False Declines Cost Th...,47% of Merchants Report False Declines Cost Th...,https://www.pymnts.com/fraud-prevention/2026/4...,2026-03-11T09:01:44.489463+00:00,https://www.pymnts.com/fraud-prevention/2026/4...,of merchants report false declines cost them s...,"[-0.01072105, -0.0031541607, -0.004979989, -0....",0.739476
2,1e1107dd8d70e1b2b4354cfb1a03f2fb89ef02cb846b38...,PYMNTS,news,2026-02-27T22:43:31+00:00,Morgan Stanley Wants to Build the Back Office ...,Morgan Stanley Wants to Build the Back Office ...,https://www.pymnts.com/cryptocurrency/2026/mor...,2026-03-02T09:01:44.601819+00:00,https://www.pymnts.com/cryptocurrency/2026/mor...,morgan stanley wants to build the back office ...,"[-0.017383078, 0.0040216837, 0.00556588, -0.09...",0.718336
3,a2b322624c7eefbba1f180f64ad12964870b5ea570aaf7...,PYMNTS,news,2026-03-01T21:30:54+00:00,Apple Set to Announce AI-Native Hardware to Un...,Apple Set to Announce AI-Native Hardware to Un...,https://www.pymnts.com/apple/2026/apple-plans-...,2026-03-02T14:01:51.078611+00:00,https://www.pymnts.com/apple/2026/apple-plans-...,apple set to announce ainative hardware to unl...,"[-0.021654325, -0.000538251, 0.005908336, -0.0...",0.692691
4,5e22f48845e7bac3e621e6fb1b0467eeecdacf9cff2a97...,PYMNTS,news,2026-02-28T01:19:27+00:00,Visa Closes Prisma and Newpay Acquisition to E...,Visa Closes Prisma and Newpay Acquisition to E...,https://www.pymnts.com/acquisitions/2026/visa-...,2026-03-02T14:01:51.078611+00:00,https://www.pymnts.com/acquisitions/2026/visa-...,visa closes prisma and newpay acquisition to e...,"[-0.021424402, 0.001383504, -0.014503705, -0.0...",0.709055

Shape of filtered_df: (720, 12)

**BERT**

In [ ]:
# work on upserting BERT embeddings, and creating a temporary dataset that only includes articles that dont' have embeddings to decrease latency time for embeddings

In [ ]:
!pip install tf-keras
!pip install transformers==4.42.0

Requirement already satisfied: tf-keras in /usr/local/lib/python3.12/dist-packages (2.19.0)
Requirement already satisfied: tensorflow<2.20,>=2.19 in /usr/local/lib/python3.12/dist-packages (from tf-keras) (2.19.0)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.20,>=2.19->tf-keras) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.20,>=2.19->tf-keras) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.20,>=2.19->tf-keras) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.20,>=2.19->tf-keras) (0.7.0)
Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.20,>=2.19->tf-keras) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.20,>=2.19->tf-keras) (18.1.1)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.20,>=2.19->tf-keras) (3.4.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.20,>=2.19->tf-keras) (26.0)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.20,>=2.19->tf-keras) (5.29.6)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.20,>=2.19->tf-keras) (2.32.4)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.20,>=2.19->tf-keras) (75.2.0)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.20,>=2.19->tf-keras) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.20,>=2.19->tf-keras) (3.3.0)
Requirement already satisfied: typing-extensions>=3.6.6 in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.20,>=2.19->tf-keras) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.20,>=2.19->tf-keras) (2.1.2)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.20,>=2.19->tf-keras) (1.78.0)
Requirement already satisfied: tensorboard~=2.19.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.20,>=2.19->tf-keras) (2.19.0)
Requirement already satisfied: keras>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.20,>=2.19->tf-keras) (3.13.2)
Requirement already satisfied: numpy<2.2.0,>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.20,>=2.19->tf-keras) (1.26.4)
Requirement already satisfied: h5py>=3.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.20,>=2.19->tf-keras) (3.16.0)
Requirement already satisfied: ml-dtypes<1.0.0,>=0.5.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow<2.20,>=2.19->tf-keras) (0.5.4)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from astunparse>=1.6.0->tensorflow<2.20,>=2.19->tf-keras) (0.46.3)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow<2.20,>=2.19->tf-keras) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow<2.20,>=2.19->tf-keras) (0.1.0)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow<2.20,>=2.19->tf-keras) (0.19.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow<2.20,>=2.19->tf-keras) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow<2.20,>=2.19->tf-keras) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow<2.20,>=2.19->tf-keras) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow<2.20,>=2.19->tf-keras) (2026.2.25)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow<2.20,>=2.19->tf-keras) (3.10.2)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow<2.20,>=2.19->tf-keras) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow<2.20,>=2.19->tf-keras) (3.1.6)
Requirement already satisfied: markupsafe>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from werkzeug>=1.0.1->tensorboard~=2.19.0->tensorflow<2.20,>=2.19->tf-keras) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.5.0->tensorflow<2.20,>=2.19->tf-keras) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.5.0->tensorflow<2.20,>=2.19->tf-keras) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras>=3.5.0->tensorflow<2.20,>=2.19->tf-keras) (0.1.2)
Requirement already satisfied: transformers==4.42.0 in /usr/local/lib/python3.12/dist-packages (4.42.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers==4.42.0) (3.25.2)
Requirement already satisfied: huggingface-hub<1.0,>=0.23.2 in /usr/local/lib/python3.12/dist-packages (from transformers==4.42.0) (0.36.2)
Requirement already satisfied: numpy<2.0,>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers==4.42.0) (1.26.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers==4.42.0) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers==4.42.0) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers==4.42.0) (2025.11.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from transformers==4.42.0) (2.32.4)
Requirement already satisfied: tokenizers<0.20,>=0.19 in /usr/local/lib/python3.12/dist-packages (from transformers==4.42.0) (0.19.1)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.12/dist-packages (from transformers==4.42.0) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers==4.42.0) (4.67.3)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.23.2->transformers==4.42.0) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.23.2->transformers==4.42.0) (1.4.2)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.23.2->transformers==4.42.0) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.42.0) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.42.0) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.42.0) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.42.0) (2026.2.25)

In [ ]:
import tf_keras
print(tf_keras.__version__)

2.19.0

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf
import transformers

In [ ]:
max_length = 128  # Maximum length of input sentence to the model.
batch_size = 32
epochs = 2

In [ ]:
class BertInputBatchGenerator(tf_keras.utils.Sequence):

    def __init__(
        self,
        sentence_pairs,
        labels,
        batch_size=batch_size,
        shuffle=True,
        include_targets=True,
    ):
        self.sentence_pairs = sentence_pairs
        self.labels = labels
        self.shuffle = shuffle
        self.batch_size = batch_size
        self.include_targets = include_targets
        # Load our BERT Tokenizer to encode the text.
        # We will use bert-base-uncased pretrained model.
        self.tokenizer = transformers.BertTokenizer.from_pretrained(
            "bert-base-uncased", do_lower_case=True
        )
        self.indexes = np.arange(len(self.sentence_pairs))
        self.on_epoch_end()

    def __len__(self):
        # Return the number of batches per epoch.
        return len(self.sentence_pairs) // self.batch_size

    def __getitem__(self, idx):
        # Retrieves the batch of index.
        indexes = self.indexes[idx * self.batch_size : (idx + 1) * self.batch_size]
        sentence_pairs = self.sentence_pairs[indexes]

        # With BERT tokenizer's batch_encode_plus, batch of both the sentences are
        # encoded together and separated by [SEP] token.
        encoded = self.tokenizer.batch_encode_plus(
            sentence_pairs.tolist(),
            add_special_tokens=True,
            max_length=max_length,
            return_attention_mask=True,
            return_token_type_ids=True,
            padding='max_length', # Changed from pad_to_max_length=True
            truncation=True, # Added truncation=True
            return_tensors="tf",
        )

        # Convert batch of encoded features to numpy array.
        input_ids = np.array(encoded["input_ids"], dtype="int32")
        attention_masks = np.array(encoded["attention_mask"], dtype="int32")
        token_type_ids = np.array(encoded["token_type_ids"], dtype="int32")

        # Set to true if the data generator is used for training/validation.
        if self.include_targets:
            labels = np.array(self.labels[indexes], dtype="int32")
            return [input_ids, attention_masks, token_type_ids], labels
        else:
            return [input_ids, attention_masks, token_type_ids]

    def on_epoch_end(self):
        # Shuffle indexes after each epoch if shuffle is set to True.
        if self.shuffle:
            np.random.RandomState(42).shuffle(self.indexes)

In [ ]:
strategy = tf.distribute.MirroredStrategy()

with strategy.scope():
    # Encoded token ids from BERT tokenizer.
    input_ids = tf_keras.Input(
        shape=(max_length,), dtype=tf.int32, name="input_ids"
    )
    # Attention masks indicate which tokens are real and which are fake (padding).
    attention_masks = tf_keras.Input(
        shape=(max_length,), dtype=tf.int32, name="attention_masks"
    )
    # Token type ids indicate which tokens belong to Sentence 1 and which to Sentence 2.
    token_type_ids = tf_keras.Input(
        shape=(max_length,), dtype=tf.int32, name="token_type_ids"
    )
    # Loading pretrained BERT model.
    bert_model = transformers.TFBertModel.from_pretrained("bert-base-uncased")
    # Freeze the BERT model to reuse the pretrained features without modifying them.
    bert_model.trainable = False

    # Explicit conversion of KerasTensors to tf.Tensors
    bert_output = bert_model.bert(
        input_ids, attention_mask=attention_masks, token_type_ids=token_type_ids
    )
    sequence_output = bert_output.last_hidden_state
    pooled_output = bert_output.pooler_output

    # Add trainable layers on top of frozen layers to adapt the pretrained features on the new data.
    bi_lstm = tf_keras.layers.Bidirectional(
        tf_keras.layers.LSTM(64, return_sequences=True)
    )(sequence_output)
    # Applying hybrid pooling approach to bi_lstm sequence output.
    avg_pool = tf_keras.layers.GlobalAveragePooling1D()(bi_lstm)
    dropout = tf_keras.layers.Dropout(0.3)(avg_pool)
    output = tf_keras.layers.Dense(3, activation="softmax")(dropout)


    model = tf_keras.Model(
        inputs=[input_ids, attention_masks, token_type_ids], outputs=output
    )

    model.compile(
        optimizer=tf_keras.optimizers.Adam(),
        loss="categorical_crossentropy",
        metrics=["acc"],
    )


print(f"Strategy: {strategy}")
model.summary()

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFBertModel: ['cls.predictions.transform.LayerNorm.bias', 'cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing TFBertModel from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
All the weights of TFBertModel were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions without further training.

Strategy: <tensorflow.python.distribute.mirrored_strategy.MirroredStrategy object at 0x789fb2b32b40>
Model: "model"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to
==================================================================================================
 input_ids (InputLayer)      [(None, 128)]                0         []

 attention_masks (InputLaye  [(None, 128)]                0         []
 r)

 token_type_ids (InputLayer  [(None, 128)]                0         []
 )

 bert (TFBertMainLayer)      TFBaseModelOutputWithPooli   1094822   ['input_ids[0][0]',
                             ngAndCrossAttentions(last_   40         'attention_masks[0][0]',
                             hidden_state=(None, 128, 7              'token_type_ids[0][0]']
                             68),
                              pooler_output=(None, 768)
                             , past_key_values=None, hi
                             dden_states=None, attentio
                             ns=None, cross_attentions=
                             None)

 bidirectional (Bidirection  (None, 128, 128)             426496    ['bert[0][0]']
 al)

 global_average_pooling1d (  (None, 128)                  0         ['bidirectional[0][0]']
 GlobalAveragePooling1D)

 dropout_37 (Dropout)        (None, 128)                  0         ['global_average_pooling1d[0][
                                                                    0]']

 dense (Dense)               (None, 3)                    387       ['dropout_37[0][0]']

==================================================================================================
Total params: 109909123 (419.27 MB)
Trainable params: 426883 (1.63 MB)
Non-trainable params: 109482240 (417.64 MB)
__________________________________________________________________________________________________

In [ ]:
tokenizer = transformers.BertTokenizer.from_pretrained(
    "bert-base-uncased", do_lower_case=True
)

encoded_data = tokenizer.batch_encode_plus(
    filtered_df['cleaned_text'].tolist(),
    add_special_tokens=True,
    max_length=max_length,
    return_attention_mask=True,
    return_token_type_ids=True,
    padding='max_length',
    truncation=True,
    return_tensors="tf",
)

df['input_ids'] = encoded_data['input_ids'].numpy().tolist()
df['attention_mask'] = encoded_data['attention_mask'].numpy().tolist()
df['token_type_ids'] = encoded_data['token_type_ids'].numpy().tolist()

display(filtered_df.head())
print("Text tokenization for BERT complete and added to DataFrame.")

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

,doc_id,source,source_type,publish_timestamp,title,raw_text,url,fetch_timestamp,raw_html,cleaned_text,text_embedding,fraud_similarity
0,a5be497f1c586e6269c0609e6fb1f591d5afc3e5790743...,PYMNTS,news,2026-03-11T08:02:09+00:00,AI Forensics Takes Aim at Compliance Gridlock,AI Forensics Takes Aim at Compliance Gridlock ...,https://www.pymnts.com/news/artificial-intelli...,2026-03-11T09:01:44.489463+00:00,https://www.pymnts.com/news/artificial-intelli...,ai forensics takes aim at compliance gridlock ...,"[-0.011796092, 0.0015656062, -0.0031555267, -0...",0.749914
1,dd8ca37af85b6c3b9a9aa93cc6b381769dfe69e767e7b1...,PYMNTS,news,2026-03-11T08:00:40+00:00,47% of Merchants Report False Declines Cost Th...,47% of Merchants Report False Declines Cost Th...,https://www.pymnts.com/fraud-prevention/2026/4...,2026-03-11T09:01:44.489463+00:00,https://www.pymnts.com/fraud-prevention/2026/4...,of merchants report false declines cost them s...,"[-0.01072105, -0.0031541607, -0.004979989, -0....",0.739476
2,1e1107dd8d70e1b2b4354cfb1a03f2fb89ef02cb846b38...,PYMNTS,news,2026-02-27T22:43:31+00:00,Morgan Stanley Wants to Build the Back Office ...,Morgan Stanley Wants to Build the Back Office ...,https://www.pymnts.com/cryptocurrency/2026/mor...,2026-03-02T09:01:44.601819+00:00,https://www.pymnts.com/cryptocurrency/2026/mor...,morgan stanley wants to build the back office ...,"[-0.017383078, 0.0040216837, 0.00556588, -0.09...",0.718336
3,a2b322624c7eefbba1f180f64ad12964870b5ea570aaf7...,PYMNTS,news,2026-03-01T21:30:54+00:00,Apple Set to Announce AI-Native Hardware to Un...,Apple Set to Announce AI-Native Hardware to Un...,https://www.pymnts.com/apple/2026/apple-plans-...,2026-03-02T14:01:51.078611+00:00,https://www.pymnts.com/apple/2026/apple-plans-...,apple set to announce ainative hardware to unl...,"[-0.021654325, -0.000538251, 0.005908336, -0.0...",0.692691
4,5e22f48845e7bac3e621e6fb1b0467eeecdacf9cff2a97...,PYMNTS,news,2026-02-28T01:19:27+00:00,Visa Closes Prisma and Newpay Acquisition to E...,Visa Closes Prisma and Newpay Acquisition to E...,https://www.pymnts.com/acquisitions/2026/visa-...,2026-03-02T14:01:51.078611+00:00,https://www.pymnts.com/acquisitions/2026/visa-...,visa closes prisma and newpay acquisition to e...,"[-0.021424402, 0.001383504, -0.014503705, -0.0...",0.709055

Text tokenization for BERT complete and added to DataFrame.

In [ ]:
from sklearn.model_selection import train_test_split
from tensorflow.keras.utils import to_categorical

# Create dummy labels for a 3-class classification problem
# In a real scenario, these labels would come from your dataset
num_classes = 3
dummy_labels = np.random.randint(0, num_classes, size=len(df))

# One-hot encode the dummy labels as required by categorical_crossentropy
ohe_labels = to_categorical(dummy_labels, num_classes=num_classes)

# Split the data into training and validation sets
X_train, X_val, y_train, y_val = train_test_split(
    filtered_df['cleaned_text'].values,
    ohe_labels,
    test_size=0.2,
    random_state=42,
    stratify=dummy_labels # Stratify based on the original dummy labels
)

print(f"Training set size: {len(X_train)} samples")
print(f"Validation set size: {len(X_val)} samples")
print(f"Shape of training labels: {y_train.shape}")

# Create data generators for training and validation
train_data_generator = BertInputBatchGenerator(
    X_train, y_train, batch_size=batch_size, shuffle=True
)
valid_data_generator = BertInputBatchGenerator(
    X_val, y_val, batch_size=batch_size, shuffle=False
)

print("BERT data generators for training and validation created.")

Training set size: 576 samples
Validation set size: 144 samples
Shape of training labels: (576, 3)
BERT data generators for training and validation created.

In [ ]:
import os

history = model.fit(
    train_data_generator,
    validation_data=valid_data_generator,
    epochs=epochs,
    use_multiprocessing=True,
    workers=os.cpu_count()
)

print("BERT model training complete.")

Epoch 1/2
18/18 [==============================] - 552s 30s/step - loss: 1.1606 - acc: 0.3056 - val_loss: 1.1058 - val_acc: 0.3359
Epoch 2/2
18/18 [==============================] - 537s 30s/step - loss: 1.0996 - acc: 0.3524 - val_loss: 1.1190 - val_acc: 0.3516
BERT model training complete.

In [ ]:
loss, accuracy = model.evaluate(valid_data_generator)
print(f"Validation Loss: {loss:.4f}")
print(f"Validation Accuracy: {accuracy:.4f}")

4/4 [==============================] - 88s 21s/step - loss: 1.1190 - acc: 0.3516
Validation Loss: 1.1190
Validation Accuracy: 0.3516

In [ ]:
bert_input_ids = tf.constant(df['input_ids'].tolist(), dtype=tf.int32)
bert_attention_masks = tf.constant(df['attention_mask'].tolist(), dtype=tf.int32)
bert_token_type_ids = tf.constant(df['token_type_ids'].tolist(), dtype=tf.int32)

# Use the bert_model.bert() function to process these inputs
bert_output = bert_model.bert(
    bert_input_ids,
    attention_mask=bert_attention_masks,
    token_type_ids=bert_token_type_ids
)

# Extract the pooled_output from the bert_output
pooled_output = bert_output.pooler_output

# Convert the pooled_output to a list of NumPy arrays and store it in a new column
filtered_df['bert_embedding'] = pooled_output.numpy().tolist()

# Display the head of the DataFrame to show the new 'bert_embedding' column
display(filtered_df.head())
print("BERT embeddings generated and added to DataFrame.")

,doc_id,source,source_type,publish_timestamp,title,raw_text,url,fetch_timestamp,raw_html,cleaned_text,text_embedding,fraud_similarity,bert_embedding
0,a5be497f1c586e6269c0609e6fb1f591d5afc3e5790743...,PYMNTS,news,2026-03-11T08:02:09+00:00,AI Forensics Takes Aim at Compliance Gridlock,AI Forensics Takes Aim at Compliance Gridlock ...,https://www.pymnts.com/news/artificial-intelli...,2026-03-11T09:01:44.489463+00:00,https://www.pymnts.com/news/artificial-intelli...,ai forensics takes aim at compliance gridlock ...,"[-0.011796092, 0.0015656062, -0.0031555267, -0...",0.749914,"[-0.6511983275413513, -0.4530746340751648, -0...."
1,dd8ca37af85b6c3b9a9aa93cc6b381769dfe69e767e7b1...,PYMNTS,news,2026-03-11T08:00:40+00:00,47% of Merchants Report False Declines Cost Th...,47% of Merchants Report False Declines Cost Th...,https://www.pymnts.com/fraud-prevention/2026/4...,2026-03-11T09:01:44.489463+00:00,https://www.pymnts.com/fraud-prevention/2026/4...,of merchants report false declines cost them s...,"[-0.01072105, -0.0031541607, -0.004979989, -0....",0.739476,"[-0.461780846118927, -0.2903430461883545, -0.8..."
2,1e1107dd8d70e1b2b4354cfb1a03f2fb89ef02cb846b38...,PYMNTS,news,2026-02-27T22:43:31+00:00,Morgan Stanley Wants to Build the Back Office ...,Morgan Stanley Wants to Build the Back Office ...,https://www.pymnts.com/cryptocurrency/2026/mor...,2026-03-02T09:01:44.601819+00:00,https://www.pymnts.com/cryptocurrency/2026/mor...,morgan stanley wants to build the back office ...,"[-0.017383078, 0.0040216837, 0.00556588, -0.09...",0.718336,"[-0.6168637275695801, -0.49527841806411743, -0..."
3,a2b322624c7eefbba1f180f64ad12964870b5ea570aaf7...,PYMNTS,news,2026-03-01T21:30:54+00:00,Apple Set to Announce AI-Native Hardware to Un...,Apple Set to Announce AI-Native Hardware to Un...,https://www.pymnts.com/apple/2026/apple-plans-...,2026-03-02T14:01:51.078611+00:00,https://www.pymnts.com/apple/2026/apple-plans-...,apple set to announce ainative hardware to unl...,"[-0.021654325, -0.000538251, 0.005908336, -0.0...",0.692691,"[-0.7074005603790283, -0.3899894058704376, -0...."
4,5e22f48845e7bac3e621e6fb1b0467eeecdacf9cff2a97...,PYMNTS,news,2026-02-28T01:19:27+00:00,Visa Closes Prisma and Newpay Acquisition to E...,Visa Closes Prisma and Newpay Acquisition to E...,https://www.pymnts.com/acquisitions/2026/visa-...,2026-03-02T14:01:51.078611+00:00,https://www.pymnts.com/acquisitions/2026/visa-...,visa closes prisma and newpay acquisition to e...,"[-0.021424402, 0.001383504, -0.014503705, -0.0...",0.709055,"[-0.6120616793632507, -0.33784258365631104, -0..."

BERT embeddings generated and added to DataFrame.

In [ ]:
from sklearn.cluster import KMeans

# Convert the list of embeddings to a NumPy array
X = np.array(filtered_df['bert_embedding'].tolist())

# Initialize KMeans model with 5 clusters and a random state for reproducibility
num_clusters = 5
kmeans = KMeans(n_clusters=num_clusters, random_state=42, n_init='auto')

# Fit the KMeans model to the BERT embeddings and get cluster labels
filtered_df['cluster_label'] = kmeans.fit_predict(X)

# Display the count of articles in each cluster
print("Distribution of articles per cluster:")
print(filtered_df['cluster_label'].value_counts())

display(filtered_df.head())

Distribution of articles per cluster:
cluster_label
2    236
3    187
0    175
1    107
4     15
Name: count, dtype: int64

,doc_id,source,source_type,publish_timestamp,title,raw_text,url,fetch_timestamp,raw_html,cleaned_text,text_embedding,fraud_similarity,bert_embedding,cluster_label
0,a5be497f1c586e6269c0609e6fb1f591d5afc3e5790743...,PYMNTS,news,2026-03-11T08:02:09+00:00,AI Forensics Takes Aim at Compliance Gridlock,AI Forensics Takes Aim at Compliance Gridlock ...,https://www.pymnts.com/news/artificial-intelli...,2026-03-11T09:01:44.489463+00:00,https://www.pymnts.com/news/artificial-intelli...,ai forensics takes aim at compliance gridlock ...,"[-0.011796092, 0.0015656062, -0.0031555267, -0...",0.749914,"[-0.6511983275413513, -0.4530746340751648, -0....",2
1,dd8ca37af85b6c3b9a9aa93cc6b381769dfe69e767e7b1...,PYMNTS,news,2026-03-11T08:00:40+00:00,47% of Merchants Report False Declines Cost Th...,47% of Merchants Report False Declines Cost Th...,https://www.pymnts.com/fraud-prevention/2026/4...,2026-03-11T09:01:44.489463+00:00,https://www.pymnts.com/fraud-prevention/2026/4...,of merchants report false declines cost them s...,"[-0.01072105, -0.0031541607, -0.004979989, -0....",0.739476,"[-0.461780846118927, -0.2903430461883545, -0.8...",0
2,1e1107dd8d70e1b2b4354cfb1a03f2fb89ef02cb846b38...,PYMNTS,news,2026-02-27T22:43:31+00:00,Morgan Stanley Wants to Build the Back Office ...,Morgan Stanley Wants to Build the Back Office ...,https://www.pymnts.com/cryptocurrency/2026/mor...,2026-03-02T09:01:44.601819+00:00,https://www.pymnts.com/cryptocurrency/2026/mor...,morgan stanley wants to build the back office ...,"[-0.017383078, 0.0040216837, 0.00556588, -0.09...",0.718336,"[-0.6168637275695801, -0.49527841806411743, -0...",3
3,a2b322624c7eefbba1f180f64ad12964870b5ea570aaf7...,PYMNTS,news,2026-03-01T21:30:54+00:00,Apple Set to Announce AI-Native Hardware to Un...,Apple Set to Announce AI-Native Hardware to Un...,https://www.pymnts.com/apple/2026/apple-plans-...,2026-03-02T14:01:51.078611+00:00,https://www.pymnts.com/apple/2026/apple-plans-...,apple set to announce ainative hardware to unl...,"[-0.021654325, -0.000538251, 0.005908336, -0.0...",0.692691,"[-0.7074005603790283, -0.3899894058704376, -0....",2
4,5e22f48845e7bac3e621e6fb1b0467eeecdacf9cff2a97...,PYMNTS,news,2026-02-28T01:19:27+00:00,Visa Closes Prisma and Newpay Acquisition to E...,Visa Closes Prisma and Newpay Acquisition to E...,https://www.pymnts.com/acquisitions/2026/visa-...,2026-03-02T14:01:51.078611+00:00,https://www.pymnts.com/acquisitions/2026/visa-...,visa closes prisma and newpay acquisition to e...,"[-0.021424402, 0.001383504, -0.014503705, -0.0...",0.709055,"[-0.6120616793632507, -0.33784258365631104, -0...",2

In [ ]:
for cluster_id in sorted(filtered_df['cluster_label'].unique()):
    print(f"\n--- Cluster {cluster_id} ---")
    cluster_sample = filtered_df[filtered_df['cluster_label'] == cluster_id].sample(min(10, len(filtered_df[filtered_df['cluster_label'] == cluster_id])), random_state=42)
    display(cluster_sample[['doc_id', 'title', 'source', 'cleaned_text']])

--- Cluster 0 ---

,doc_id,title,source,cleaned_text
627,99b111433bfff4f41d3ce5d5c3d298fdb534efd917b34f...,Shopify Signals Stablecoin Preferences With US...,PYMNTS,shopify signals stablecoin preferences with us...
586,3c1fab82c15e99407196ec69ee1a6cd100fc630dc4db40...,Mastercard Expands Gen AI Push With Model Buil...,PYMNTS,mastercard expands gen ai push with model buil...
416,ae1827214cc181ef648057b3e8a2f7d7948b479b560016...,Stripe Introduces Billing Tools to Meter and C...,PYMNTS,stripe introduces billing tools to meter and c...
510,3c8407abf0c789704e7d4f1927ad0f0a0c4d2def71b4c6...,How CFOs Are Turning Working Capital Into a Yi...,PYMNTS,how cfos are turning working capital into a yi...
562,9d286c6e1682c5736a8c71657e8e7f0c654f2d6dfe5b5a...,13 States Sue Lender OneMain Financial Over Al...,PYMNTS,states sue lender onemain financial over alleg...
556,a4646aa6e2dc2333e2be70e916f7b76197202b6e8ebf3d...,Walmart Shuts Down Agentic Commerce With OpenAI,PYMNTS,walmart shuts down agentic commerce with opena...
166,98bb79fef1dd878c2401990d4953dea45b96ec571c4315...,New SEC Guidance Pushes Stablecoins Closer to ...,PYMNTS,new sec guidance pushes stablecoins closer to ...
56,5541a85b7c8466b717d546aed5d48786c5155de754526c...,Klarna Hits First $1 Billion Revenue Quarter a...,PYMNTS,klarna hits first billion revenue quarter as b...
509,d50f43fec53cccd54bfb9be189645891c3a10b9552e526...,FedEx Plans Agent Workforce in Over 50% of Wor...,PYMNTS,fedex plans agent workforce in over of workflo...
282,d027d2d8375daa6ff41ad295535122c669d056ba07959a...,Kraken First Digital Asset Bank to Gain Fed Pa...,PYMNTS,kraken first digital asset bank to gain fed pa...

--- Cluster 1 ---

,doc_id,title,source,cleaned_text
580,ec774317494a188fe4d314a44d35b6d4d48e783ee7775f...,Kalshi Tech Aims to Prevent Insider Trading,PYMNTS,kalshi tech aims to prevent insider trading ka...
90,4d28f84f5cb99cdc3ddf49cb7a1acd0d18e0fe91684804...,ByteDance Valuation Hits $550 Billion in Plann...,PYMNTS,bytedance valuation hits billion in planned sh...
33,6abb758b550d2ab478cafc5c28ba40bd3d825ec1062488...,How Hidden Prompts Are Influencing Enterprise ...,PYMNTS,how hidden prompts are influencing enterprise ...
694,b829ffe53014e92ca0d06ed75f73fadb06958cd394d147...,Delve accused of misleading customers with ‘fa...,TechCrunch,an anonymous substack post published this week...
537,b500e7461836814142634f8cf98d4fa9ba144a7323985b...,The Digital Economy’s Longest-Running Grudge M...,PYMNTS,the digital economys longestrunning grudge mat...
525,7b653c9f6e55de42452a604fd3f5925d705d54a4640836...,Walmart’s PhonePe Says War Has Halted IPO Plans,PYMNTS,walmarts phonepe says war has halted ipo plans...
264,397b9038f17cb7c9482b22149ff1e66ce05b3b433eb398...,Prediction Markets Face Congressional Scrutiny...,PYMNTS,prediction markets face congressional scrutiny...
371,98a2f6c324d2d19ce0483553eb102eed2435f7e022d0fe...,White House Warns of Lengthy Tariff Refund Tim...,PYMNTS,white house warns of lengthy tariff refund tim...
651,d7fe5a1a6f990b97cd9db9e50b5113f0cf4cc20c3ff183...,Spotify Leans on AI to Keep Subscribers Listening,PYMNTS,spotify leans on ai to keep subscribers listen...
91,df08aba724175e632713c81119cd03144d26f97cfaaf43...,Healthy Small Businesses Report 42-Point Edge ...,PYMNTS,healthy small businesses report point edge in ...

--- Cluster 2 ---

,doc_id,title,source,cleaned_text
207,545f22b5c13d826f967ca8d6e26af06a92f13f4a9ccf6c...,AI Disruption Debate Roils Markets and Refocus...,PYMNTS,ai disruption debate roils markets and refocus...
578,e926526a400feec2ed0a3017c5553fe190ebd513ddfef8...,Insurance Faces a New Threat That Looks Like a...,PYMNTS,insurance faces a new threat that looks like a...
558,5f1f4a117fda21c23fbc2fe284518fbd6e02f2c1ac6519...,Amazon Brings 1-Hour Delivery to Hundreds of C...,PYMNTS,amazon brings hour delivery to hundreds of cit...
27,b901a5e0bbd141c47be622420d0df4f2d2ad4299040dbb...,Fiserv Catches Eye of Activist Investor Jana P...,PYMNTS,fiserv catches eye of activist investor jana p...
384,5760b320fc0a9011dbdd437498f782ce3a00159d916c78...,Gen Z Turns Mobile Apps and Credit Into Financ...,PYMNTS,gen z turns mobile apps and credit into financ...
321,040539e33c9d7bb6a7e4f7117444fe2e189cae6f1373fb...,Bank of America Targets the $600 Billion Accou...,PYMNTS,bank of america targets the billion accounts r...
704,5062cbd77c55921cf84d36d14d956fc9e644f43aa2c0ff...,Apple rolls out first ‘background security’ up...,TechCrunch,apple has published its first background secur...
259,25dc0cfb1b6be85838bed50345f01963f8126e528eea60...,FinTechs Strengthen Compliance as Embedded Fin...,PYMNTS,fintechs strengthen compliance as embedded fin...
450,2c3c31b515f8ce4a85e5f7df4d6e2589cd1bf31ebbc4bf...,Papa John’s Thinks the Next Great Pizza Toppin...,PYMNTS,papa johns thinks the next great pizza topping...
44,3831c2f7197529ce39c7ca002144c6e4d93d2a77b77d94...,What Happens to Stores When AI Agents Do the S...,PYMNTS,what happens to stores when ai agents do the s...

--- Cluster 3 ---

,doc_id,title,source,cleaned_text
707,5e064b617f5f5fb8a38c56bd62f4b0622c8992db6f0b6c...,The FBI is investigating malware hidden inside...,TechCrunch,the fbi is investigating a hacker suspected of...
286,9cc2fd1e81642744390e440170498eab3080b9c5b245c7...,American Factories Reverse 40-Month Slump With...,PYMNTS,american factories reverse month slump with ne...
206,4996b4be78fe4392e3cb0cf4359ce4f05561a556e65ac3...,Installment Payments Come to Luxury Retail as ...,PYMNTS,installment payments come to luxury retail as ...
499,f20b7a8dc5255e72f1a86e4192a2a80b1a7b00ebf7a9a0...,Why Millions of New Accounts Never Turn Into R...,PYMNTS,why millions of new accounts never turn into r...
614,1ff558c4059143105145b17dbc8c7eace8cfd46c6a6d09...,Mastercard’s BVNK Deal Highlights the 4 Barrie...,PYMNTS,mastercards bvnk deal highlights the barriers ...
60,0e9eef5d586e59e4dd10f0a178ebdd3aef0f73c2c500e8...,"Behind the Stablecoin Buzz, Old-School Infrast...",PYMNTS,behind the stablecoin buzz oldschool infrastru...
274,3191e8d7c12f38798d8d8004dea6c51c8e6ad7e48149a7...,From Water Breaks to Handshakes: How Predictio...,PYMNTS,from water breaks to handshakes how prediction...
574,e395f58a4c390cecda03514aa094fc8897d7ba052d158e...,Credit Applications Hit 3-Year Peak as Banks S...,PYMNTS,credit applications hit year peak as banks sla...
451,05409ed6f4ad1659764efa95a1d7ea0d0cfa3ca005a552...,"AWS, Google Signal Healthcare’s Shift to Agent...",PYMNTS,aws google signal healthcares shift to agentic...
661,5b4cfac9556a74c946a37d56b5e0641211afe45b95aba8...,50% of CFOs Say AI Will Create New Workforce R...,PYMNTS,of cfos say ai will create new workforce roles...

--- Cluster 4 ---

,doc_id,title,source,cleaned_text
445,12b19b39e9b38e40c810c3e9558665b39b84c7a5a8b404...,Gen Z Goes Big for Legacy Brands as Malls Make...,PYMNTS,gen z goes big for legacy brands as malls make...
560,e3d3175b37d8f24161716ada2611e274f33ca699e4da01...,75% of Consumers Say Inflation Coping Strategi...,PYMNTS,of consumers say inflation coping strategies a...
112,c133d9dc6b81b6b49e085dab2b81eda2caa3522e2a092c...,OpenAI Inks Deal With Pentagon Amid Anthropic ...,PYMNTS,openai inks deal with pentagon amid anthropic ...
599,c27a9da82967f57d2587136f0ac315a2414ef3a98150f1...,Credit Unions Prepare for the Day AI Agents St...,PYMNTS,credit unions prepare for the day ai agents st...
267,55a664c82f79116054958e0bd91381e06632dd88b0e918...,BofA Economists See AI Creating New Types of Jobs,PYMNTS,bofa economists see ai creating new types of j...
341,ec4441f1f6dc89b1d1a899c8f2225b7fc9ec71b0f648eb...,Marketing’s AI Shift Is From Measuring Campaig...,PYMNTS,marketings ai shift is from measuring campaign...
149,456cb0508b704c73e09dbaf75bc67f1a2483f1f9928e74...,Samsung and Perplexity Push New Agentic Tools ...,PYMNTS,samsung and perplexity push new agentic tools ...
147,1db850e2c5f95fe5228e7024f0d9446c6d77a69721f354...,OpenAI Intelligence Report Identifies New Tact...,PYMNTS,openai intelligence report identifies new tact...
715,9b860322fd5c41ee133d472d9c2588fdb997303dec6b17...,OpenAI acquires Promptfoo to secure its AI agents,TechCrunch,openai announced monday it has acquired prompt...
224,701b05064fcba9452630e23cc2d73a27f196e2d951735e...,Anthropic Sees Clients Step Back Following Gov...,PYMNTS,anthropic sees clients step back following gov...

In [ ]:
import hdbscan

clusterer = hdbscan.HDBSCAN(min_cluster_size=6)
labels = clusterer.fit_predict(X)

/usr/local/lib/python3.12/dist-packages/hdbscan/robust_single_linkage_.py:175: SyntaxWarning: invalid escape sequence '\{'
  $max \{ core_k(a), core_k(b), 1/\alpha d(a,b) \}$.

In [ ]:
filtered_df['hdbscan_cluster_label'] = labels
print("HDBSCAN cluster labels added to DataFrame.")

HDBSCAN cluster labels added to DataFrame.

In [ ]:
print("Distribution of articles per HDBSCAN cluster:")
print(filtered_df['hdbscan_cluster_label'].value_counts())

# Display sample articles for each HDBSCAN cluster, excluding noise points (-1)
for cluster_id in sorted(filtered_df['hdbscan_cluster_label'].unique()):
    if cluster_id != -1: # Exclude noise points
        print(f"\n--- HDBSCAN Cluster {cluster_id} ---")
        cluster_sample = filtered_df[filtered_df['hdbscan_cluster_label'] == cluster_id].sample(min(10, len(filtered_df[filtered_df['hdbscan_cluster_label'] == cluster_id])), random_state=42)
        display(cluster_sample[['doc_id', 'title', 'source', 'cleaned_text']])

Distribution of articles per HDBSCAN cluster:
hdbscan_cluster_label
-1    638
 1     73
 0      9
Name: count, dtype: int64

--- HDBSCAN Cluster 0 ---

,doc_id,title,source,cleaned_text
544,13345e29de28494187b4cc784d2a720f54643d9528f2a2...,AI Finds the Cracks Between Login and Payment,PYMNTS,ai finds the cracks between login and payment ...
218,c7b46d85c4dd1f5d1da564103ed40397c2c08a10d359ce...,Embedded Finance Firms Brace for Tighter US Re...,PYMNTS,embedded finance firms brace for tighter us re...
482,95c16f3d92bec387a9b922302a010faad9904913eb702b...,AI Wants the Checkout but Spreedly Says Mercha...,PYMNTS,ai wants the checkout but spreedly says mercha...
177,1a159379d7f41900d2f6e74c5f9e0dedac180c901268bd...,Banks Win When They Connect Risk Signals Acros...,PYMNTS,banks win when they connect risk signals acros...
660,1a51272d7d6a454feaf1d32ab5e6aaa4ad8bf61ed3197b...,Banks Turn to Real-Time Payments to Win Small ...,PYMNTS,banks turn to realtime payments to win small b...
321,040539e33c9d7bb6a7e4f7117444fe2e189cae6f1373fb...,Bank of America Targets the $600 Billion Accou...,PYMNTS,bank of america targets the billion accounts r...
386,0470625dfdd66d85ecc586bccb31f39a7c5704b54968b1...,FedNow Pushes FEMA Disaster Aid From Days to S...,PYMNTS,fednow pushes fema disaster aid from days to s...
324,6cf0c8c24f23d90b97503013f5ca4c043a3e8f812bdb29...,OpenAI Reworks Product Strategy Around New Des...,PYMNTS,openai reworks product strategy around new des...
516,0ee02d0028c4e2d64a2c794783d1e40301bba890ae76fb...,Wallets Raise the Bar While Regulation Splits ...,PYMNTS,wallets raise the bar while regulation splits ...

--- HDBSCAN Cluster 1 ---

,doc_id,title,source,cleaned_text
32,9168c19658180123ce8528572e47c876e99c3df5b1972b...,Former Google DeepMind Scientist Targets $4 Bi...,PYMNTS,former google deepmind scientist targets billi...
586,3c1fab82c15e99407196ec69ee1a6cd100fc630dc4db40...,Mastercard Expands Gen AI Push With Model Buil...,PYMNTS,mastercard expands gen ai push with model buil...
162,88fcb032249a0cc84a74eedf83919120909886629bbf5d...,JPMorgan’s Dimon Positions AI as Competitive B...,PYMNTS,jpmorgans dimon positions ai as competitive ba...
9,220b57284c8b11a97db33fe764b9d6cbae6a74189c2985...,Banks Rethink Fraud Controls as False Declines...,PYMNTS,banks rethink fraud controls as false declines...
246,a8fc4a6d61bac1f07d51f553cea99a2ec4c76e18d2c52d...,Block Slashes Staff as Primary Banking Actives...,PYMNTS,block slashes staff as primary banking actives...
680,29224d26ba239bb077a4c00ee69e7cbf02c4e0454fad92...,Adonis Raises $40 Million for AI-Powered Healt...,PYMNTS,adonis raises million for aipowered healthcare...
72,f038ea0582a1793044a23f5f839407f33444367be53f22...,"For B2B Payments, Speed Is the New Strategy",PYMNTS,for bb payments speed is the new strategy high...
288,82924123a57a7ece5e00a296ed586683d11eca2e5c57da...,Block Strategy Points to AI Shaping Corporate ...,PYMNTS,block strategy points to ai shaping corporate ...
92,ed0f5dad017673871df25128edde0d4d363793977e2b85...,Mercado Libre Says AI Investments Support 45% ...,PYMNTS,mercado libre says ai investments support reve...
473,0a65c434d0e86e021d87c36c9b72f78e9fd75fe981bed2...,Forward-Deployed Engineers Emerge as One of AI...,PYMNTS,forwarddeployed engineers emerge as one of ais...

If HDBSCAN labels points as -1 (noise): Potential new fraud pattern

In [ ]:
# if cluster spikes, potentially an emerging threat
filtered_df['publish_timestamp'] = pd.to_datetime(filtered_df['publish_timestamp'])
filtered_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 720 entries, 0 to 719
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   doc_id                 720 non-null    object
 1   source                 720 non-null    object
 2   source_type            720 non-null    object
 3   publish_timestamp      696 non-null    datetime64[ns, UTC]
 4   title                  720 non-null    object
 5   raw_text               720 non-null    object
 6   url                    720 non-null    object
 7   fetch_timestamp        720 non-null    object
 8   raw_html               720 non-null    object
 9   cleaned_text           720 non-null    object
 10  text_embedding         720 non-null    object
 11  fraud_similarity       720 non-null    float64
 12  bert_embedding         720 non-null    object
 13  cluster_label          720 non-null    int32
 14  hdbscan_cluster_label  720 non-null    int64
dtypes: datetime64[ns, UTC](1), float64(1), int32(1), int64(1), object(11)
memory usage: 81.7+ KB

In [ ]:
filtered_df['week'] = filtered_df['publish_timestamp'].dt.isocalendar().week
display(filtered_df.head())

,doc_id,source,source_type,publish_timestamp,title,raw_text,url,fetch_timestamp,raw_html,cleaned_text,text_embedding,fraud_similarity,bert_embedding,cluster_label,hdbscan_cluster_label,week
0,a5be497f1c586e6269c0609e6fb1f591d5afc3e5790743...,PYMNTS,news,2026-03-11 08:02:09+00:00,AI Forensics Takes Aim at Compliance Gridlock,AI Forensics Takes Aim at Compliance Gridlock ...,https://www.pymnts.com/news/artificial-intelli...,2026-03-11T09:01:44.489463+00:00,https://www.pymnts.com/news/artificial-intelli...,ai forensics takes aim at compliance gridlock ...,"[-0.011796092, 0.0015656062, -0.0031555267, -0...",0.749914,"[-0.6511983275413513, -0.4530746340751648, -0....",2,-1,11
1,dd8ca37af85b6c3b9a9aa93cc6b381769dfe69e767e7b1...,PYMNTS,news,2026-03-11 08:00:40+00:00,47% of Merchants Report False Declines Cost Th...,47% of Merchants Report False Declines Cost Th...,https://www.pymnts.com/fraud-prevention/2026/4...,2026-03-11T09:01:44.489463+00:00,https://www.pymnts.com/fraud-prevention/2026/4...,of merchants report false declines cost them s...,"[-0.01072105, -0.0031541607, -0.004979989, -0....",0.739476,"[-0.461780846118927, -0.2903430461883545, -0.8...",0,-1,11
2,1e1107dd8d70e1b2b4354cfb1a03f2fb89ef02cb846b38...,PYMNTS,news,2026-02-27 22:43:31+00:00,Morgan Stanley Wants to Build the Back Office ...,Morgan Stanley Wants to Build the Back Office ...,https://www.pymnts.com/cryptocurrency/2026/mor...,2026-03-02T09:01:44.601819+00:00,https://www.pymnts.com/cryptocurrency/2026/mor...,morgan stanley wants to build the back office ...,"[-0.017383078, 0.0040216837, 0.00556588, -0.09...",0.718336,"[-0.6168637275695801, -0.49527841806411743, -0...",3,-1,9
3,a2b322624c7eefbba1f180f64ad12964870b5ea570aaf7...,PYMNTS,news,2026-03-01 21:30:54+00:00,Apple Set to Announce AI-Native Hardware to Un...,Apple Set to Announce AI-Native Hardware to Un...,https://www.pymnts.com/apple/2026/apple-plans-...,2026-03-02T14:01:51.078611+00:00,https://www.pymnts.com/apple/2026/apple-plans-...,apple set to announce ainative hardware to unl...,"[-0.021654325, -0.000538251, 0.005908336, -0.0...",0.692691,"[-0.7074005603790283, -0.3899894058704376, -0....",2,-1,9
4,5e22f48845e7bac3e621e6fb1b0467eeecdacf9cff2a97...,PYMNTS,news,2026-02-28 01:19:27+00:00,Visa Closes Prisma and Newpay Acquisition to E...,Visa Closes Prisma and Newpay Acquisition to E...,https://www.pymnts.com/acquisitions/2026/visa-...,2026-03-02T14:01:51.078611+00:00,https://www.pymnts.com/acquisitions/2026/visa-...,visa closes prisma and newpay acquisition to e...,"[-0.021424402, 0.001383504, -0.014503705, -0.0...",0.709055,"[-0.6120616793632507, -0.33784258365631104, -0...",2,-1,9

In [ ]:
cluster_counts_by_week = filtered_df.groupby(['week', 'hdbscan_cluster_label']).size().reset_index(name='count')
display(cluster_counts_by_week)

    week  hdbscan_cluster_label  count
0      8                     -1     66
1      8                      1      9
2      9                     -1    115
3      9                      0      2
4      9                      1     22
5     10                     -1    120
6     10                      0      1
7     10                      1     12
8     11                     -1    110
9     11                      0      3
10    11                      1     13
11    12                     -1    136
12    12                      0      2
13    12                      1      8
14    13                     -1     67
15    13                      0      1
16    13                      1      9

In [ ]:
# Create time component that tracks established threat/emerging threat
filtered_df['week'] = filtered_df['publish_timestamp'].dt.to_period('W')

/tmp/ipykernel_24119/3093011035.py:2: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  filtered_df['week'] = filtered_df['publish_timestamp'].dt.to_period('W')

In [ ]:
cluster_stats_list = []

for week in sorted(filtered_df['week'].unique()):
    weekly_df = filtered_df[filtered_df['week'] == week]

    for cluster_id in sorted(weekly_df['hdbscan_cluster_label'].unique()):
        # Exclude noise points (cluster_id == -1)
        if cluster_id != -1:
            cluster_df = weekly_df[weekly_df['hdbscan_cluster_label'] == cluster_id]

            number_of_articles = len(cluster_df)

            # Ensure there are articles in the cluster before calculating mean embedding
            if number_of_articles > 0:
                # Convert list of embeddings to a NumPy array for mean calculation
                embeddings_array = np.array(cluster_df['bert_embedding'].tolist())
                mean_embedding = embeddings_array.mean(axis=0)

                cluster_stats_list.append({
                    "week": week,
                    "cluster_id": cluster_id,
                    "count": number_of_articles,
                    "centroid": mean_embedding.tolist() # Store as list for DataFrame compatibility
                })

# Convert the list of dictionaries to a DataFrame for easier analysis
cluster_stats_df = pd.DataFrame(cluster_stats_list)

print("Cluster statistics calculated and stored in 'cluster_stats_df'.")
display(cluster_stats_df.head())

Cluster statistics calculated and stored in 'cluster_stats_df'.

,week,cluster_id,count,centroid
0,2026-02-16/2026-02-22,1,9,"[-0.6964739759763082, -0.4085484312640296, -0...."
1,2026-02-23/2026-03-01,0,2,"[-0.6520355939865112, -0.43283723294734955, -0..."
2,2026-02-23/2026-03-01,1,22,"[-0.6573318920352242, -0.39439004388722504, -0..."
3,2026-03-02/2026-03-08,0,1,"[-0.6726356744766235, -0.38949593901634216, -0..."
4,2026-03-02/2026-03-08,1,12,"[-0.667968804637591, -0.4165812705953916, -0.9..."

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

cluster_trends_data = []

for cluster_id in sorted(filtered_df['hdbscan_cluster_label'].unique()):
    if cluster_id == -1: # Skip noise points
        continue

    cluster_data = cluster_stats_df[cluster_stats_df['cluster_id'] == cluster_id].sort_values(by='week')

    cluster_data['week_timestamp'] = cluster_data['week'].dt.to_timestamp()

    if len(cluster_data) < 2:
        continue

    first_week_timestamp = cluster_data['week_timestamp'].iloc[0]

    prev_count = None
    prev_centroid = None
    prev_growth = None

    for index, row in cluster_data.iterrows():
        current_week = row['week']
        current_week_timestamp = row['week_timestamp']
        current_count = row['count']
        current_centroid = np.array(row['centroid']).reshape(1, -1)

        age_days = (current_week_timestamp - first_week_timestamp).days

        growth = 0.0
        drift = 0.0
        acceleration = 0.0

        if prev_count is not None:
            # Calculate growth
            if prev_count != 0:
                growth = (current_count - prev_count) / prev_count
            else:
                growth = np.inf # Handle division by zero

            # Calculate drift
            drift = 1 - cosine_similarity(current_centroid, prev_centroid)[0][0]

            # Calculate acceleration
            if prev_growth is not None:
                acceleration = growth - prev_growth

            cluster_trends_data.append({
                "week": current_week,
                "cluster_id": cluster_id,
                "age_days": age_days,
                "growth": growth,
                "drift": drift,
                "acceleration": acceleration
            })

        prev_count = current_count
        prev_centroid = current_centroid
        prev_growth = growth

cluster_trends_df = pd.DataFrame(cluster_trends_data)

print("Cluster trends calculated successfully.")
display(cluster_trends_df.head())

Cluster trends calculated successfully.

,week,cluster_id,age_days,growth,drift,acceleration
0,2026-03-02/2026-03-08,0,7,-0.500000,0.007071,-0.500000
1,2026-03-09/2026-03-15,0,14,2.000000,0.007149,2.500000
2,2026-03-16/2026-03-22,0,21,-0.333333,0.004066,-2.333333
3,2026-03-23/2026-03-29,0,28,-0.500000,0.006351,-0.166667
4,2026-02-23/2026-03-01,1,7,1.444444,0.001122,1.444444

In [ ]:
def classify_stage(age_days, growth, acceleration, drift):

    if growth < -0.2:
        return "declining" # decay detection

    if age_days <= 30:
        if growth > 0.3 or drift > 0.2:
            return "emerging"

    elif 30 < age_days <= 90:
        if growth > 0.1:
            return "trending"

    elif age_days >= 180:
        if acceleration < 0.05:
            return "established"

    return "stable"

In [ ]:
cluster_trends_df['stage'] = cluster_trends_df.apply(lambda row: classify_stage(
    row['age_days'],
    row['growth'],
    row['acceleration'],
    row['drift']
), axis=1)

print("Cluster stages classified successfully.")
display(cluster_trends_df.head())

Cluster stages classified successfully.

,week,cluster_id,age_days,growth,drift,acceleration,stage
0,2026-03-02/2026-03-08,0,7,-0.500000,0.007071,-0.500000,declining
1,2026-03-09/2026-03-15,0,14,2.000000,0.007149,2.500000,emerging
2,2026-03-16/2026-03-22,0,21,-0.333333,0.004066,-2.333333,declining
3,2026-03-23/2026-03-29,0,28,-0.500000,0.006351,-0.166667,declining
4,2026-02-23/2026-03-01,1,7,1.444444,0.001122,1.444444,emerging

In [ ]:
cluster_trends_df['risk_score'] = (
    0.4 * cluster_trends_df['growth'] +
    0.3 * cluster_trends_df['acceleration'] +
    0.3 * cluster_trends_df['drift']
)

print("Risk scores calculated and added to 'cluster_trends_df'.")
display(cluster_trends_df.head())

Risk scores calculated and added to 'cluster_trends_df'.

,week,cluster_id,age_days,growth,drift,acceleration,stage,risk_score
0,2026-03-02/2026-03-08,0,7,-0.500000,0.007071,-0.500000,declining,-0.347879
1,2026-03-09/2026-03-15,0,14,2.000000,0.007149,2.500000,emerging,1.552145
2,2026-03-16/2026-03-22,0,21,-0.333333,0.004066,-2.333333,declining,-0.832114
3,2026-03-23/2026-03-29,0,28,-0.500000,0.006351,-0.166667,declining,-0.248095
4,2026-02-23/2026-03-01,1,7,1.444444,0.001122,1.444444,emerging,1.011448

In [ ]:
print("Distribution of cluster stages:")
print(cluster_trends_df['stage'].value_counts())

Distribution of cluster stages:
stage
declining    5
emerging     2
stable       1
trending     1
Name: count, dtype: int64

In [ ]:
print("Descriptive statistics for 'risk_score':")
display(cluster_trends_df['risk_score'].describe())

Descriptive statistics for 'risk_score':

count    9.000000
mean     0.054280
std      0.791424
min     -0.832114
25%     -0.347879
50%     -0.248095
75%      0.203339
max      1.552145
Name: risk_score, dtype: float64

Metrics to Evaluate

Clustering quality: Silhouette score and Cluster coherence (manual labeling)

Retrieval quality: Precision@k and Recall@k

Trend detection: % of known fraud events detected early

In [ ]:
from sklearn.metrics import silhouette_score

# Filter out noise points (cluster_id == -1)
non_noise_indices = labels != -1
X_filtered = X[non_noise_indices]
labels_filtered = labels[non_noise_indices]

# Calculate the Silhouette Score for non-noise points
# Only calculate if there is more than one cluster and at least two samples
if len(np.unique(labels_filtered)) > 1 and len(labels_filtered) > 1:
    silhouette_avg = silhouette_score(X_filtered, labels_filtered)
    print(f"Silhouette Score: {silhouette_avg:.4f}")
else:
    print("Cannot calculate Silhouette Score: not enough distinct clusters or samples after removing noise.")

Silhouette Score: 0.2023

# work on this by optimizing clustering parameters

In [ ]:
import numpy as np

query = "What are emerging fraud threats?"
query_embedding = get_gemini_embeddings(query)

# Convert query_embedding to a NumPy array
query_embedding = np.array(query_embedding)

print("Query embedding generated successfully.")
print(f"Shape of query_embedding: {query_embedding.shape}")

Query embedding generated successfully.
Shape of query_embedding: (3072,)

In [ ]:
print("Analyzing 'emerging' clusters from cluster_trends_df:")
emerging_clusters_df = cluster_trends_df[cluster_trends_df['stage'] == 'emerging']
display(emerging_clusters_df)

if emerging_clusters_df.empty:
    print("No 'emerging' clusters found.")
else:
    print(f"Found {len(emerging_clusters_df)} 'emerging' clusters.")

Analyzing 'emerging' clusters from cluster_trends_df:

,week,cluster_id,age_days,growth,drift,acceleration,stage,risk_score
1,2026-03-09/2026-03-15,0,14,2.000000,0.007149,2.500000,emerging,1.552145
4,2026-02-23/2026-03-01,1,7,1.444444,0.001122,1.444444,emerging,1.011448

Found 2 'emerging' clusters.

In [ ]:
def get_bert_query_embedding(text):
    inputs = tokenizer.encode_plus(
        text,
        add_special_tokens=True,
        max_length=max_length,
        return_attention_mask=True,
        return_token_type_ids=True,
        padding='max_length',
        truncation=True,
        return_tensors="tf",
    )

    # Use the bert_model.bert() function to process these inputs
    bert_output = bert_model.bert(
        inputs['input_ids'],
        attention_mask=inputs['attention_mask'],
        token_type_ids=inputs['token_type_ids']
    )

    # Extract the pooled_output from the bert_output
    pooled_output = bert_output.pooler_output
    return pooled_output.numpy().flatten()

print("Function 'get_bert_query_embedding' defined.")

Function 'get_bert_query_embedding' defined.

In [ ]:
query = "What are emerging fraud threats?"
bert_query_embedding = get_bert_query_embedding(query)

# 3. Calculate the centroid for each HDBSCAN cluster
hdbscan_cluster_centroids = {}
for cluster_id in filtered_df['hdbscan_cluster_label'].unique():
    if cluster_id != -1:  # Exclude noise points
        cluster_embeddings = np.array(filtered_df[filtered_df['hdbscan_cluster_label'] == cluster_id]['bert_embedding'].tolist())
        if len(cluster_embeddings) > 0:
            hdbscan_cluster_centroids[cluster_id] = cluster_embeddings.mean(axis=0)

# 4. Convert to NumPy arrays
hdbscan_centroids_array = np.array(list(hdbscan_cluster_centroids.values()))
hdbscan_cluster_ids_array = np.array(list(hdbscan_cluster_centroids.keys()))

# 5. Calculate cosine similarity between query embedding and cluster centroids
query_embedding_reshaped = bert_query_embedding.reshape(1, -1)
centroid_similarities = cosine_similarity(query_embedding_reshaped, hdbscan_centroids_array).flatten()

# 6. Identify the top 3 most similar HDBSCAN clusters
top_k = 3
top_cluster_indices = centroid_similarities.argsort()[-top_k:][::-1] # Get indices of top k and reverse to get highest first
top_hdbscan_cluster_ids = hdbscan_cluster_ids_array[top_cluster_indices]

print(f"Top {top_k} most similar HDBSCAN clusters to the query: {top_hdbscan_cluster_ids}")

# 7. Filter the filtered_df to include only articles that belong to these top clusters
articles_in_top_clusters_df = filtered_df[filtered_df['hdbscan_cluster_label'].isin(top_hdbscan_cluster_ids)].copy()

# 8. Calculate the cosine similarity between query embedding and article embeddings in filtered DataFrame
article_embeddings_array = np.array(articles_in_top_clusters_df['bert_embedding'].tolist())
article_similarities = cosine_similarity(query_embedding_reshaped, article_embeddings_array).flatten()
articles_in_top_clusters_df['query_similarity'] = article_similarities

# 9. Retrieve and display the doc_id, title, and cleaned_text of the top 5 articles
top_n = 5
top_articles = articles_in_top_clusters_df.sort_values(by='query_similarity', ascending=False).head(top_n)

print(f"\nTop {top_n} articles related to '{query}':")
display(top_articles[['doc_id', 'title', 'cleaned_text', 'query_similarity']])

Top 3 most similar HDBSCAN clusters to the query: [1 0]

Top 5 articles related to 'What are emerging fraud threats?':

,doc_id,title,cleaned_text,query_similarity
74,64ff936b09d376b7742da0d1faf2ca655aa2cd3ea4a834...,Marqeta Earnings Point to BNPL Growth and Embe...,marqeta earnings point to bnpl growth and embe...,0.950267
478,3288c3e3906ae02436594ff8a44540baacad1d74997167...,Why Companies Are Racing to Centralize Treasur...,why companies are racing to centralize treasur...,0.948826
680,29224d26ba239bb077a4c00ee69e7cbf02c4e0454fad92...,Adonis Raises $40 Million for AI-Powered Healt...,adonis raises million for aipowered healthcare...,0.948154
555,d6a1f4f25e54b6746237d27a0221c366195a011690ec3a...,85% of Merchants Say Fraud Tools Must Reduce C...,of merchants say fraud tools must reduce check...,0.945332
124,aee353bb556a733f7b80b5d8b9571fe2b7e13b21e13455...,Anthropic Debuts Security Tool as Cybersecurit...,anthropic debuts security tool as cybersecurit...,0.944047

To be run in SQL Editor in Supabase:



```
create extension if not exists vector;

create table documents (
  id uuid primary key default gen_random_uuid(),
  content text,
  embedding vector(768), # depends on model
  cluster int,
  metadata jsonb
);


create index on documents
using ivfflat (embedding vector_cosine_ops)
with (lists = 100);


select content, cluster
from documents
order by embedding <-> '[query_vector]'
limit 5;


select content
from documents
where cluster in (1, 3, 7)
order by embedding <-> '[query_vector]'
limit 5;
```

What was run in the sql editor
```
-- Enable pgvector
create extension if not exists vector;

-- Add cluster column for DBSCAN results
alter table article_embeddings
add column if not exists cluster int;

-- Check embedding dimensions
select vector_dims(embedding)
from article_embeddings
limit 5;

-- Working semantic search query
with query_vector as (
  select ('[' || string_agg('0', ',') || ']')::vector as v
  from generate_series(1, 3072)
)
select
  a.doc_id,
  a.title,
  a.raw_text
from article_embeddings e
join articles_v1 a
  on a.doc_id = e.doc_id,
query_vector q
order by e.embedding <-> q.v
limit 5;

```

In [ ]:
cluster_centers = kmeans.cluster_centers_
similarities = cosine_similarity(cluster_centers, bert_query_embedding.reshape(1, -1)).flatten()
top_clusters = similarities.argsort()[-3:]

In [ ]:
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

cluster_centers = kmeans.cluster_centers_
similarities = cosine_similarity(cluster_centers, bert_query_embedding.reshape(1, -1)).flatten()
top_clusters = similarities.argsort()[-3:]

In [ ]:
filtered_indices = [
    i for i, m in enumerate(metadata)
    if m["cluster_label"] in top_clusters # Changed 'cluster' to 'cluster_label'
]

filtered_embeddings = embeddings[filtered_indices]

In [ ]:
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

# Identify articles belonging to the top K-Means clusters
# 'top_clusters' is derived from the K-Means similarity calculation (variable `top_clusters` from cell _kAoGNvZGPyg)
articles_in_kmeans_top_clusters_df = filtered_df[filtered_df['cluster_label'].isin(top_clusters)].copy()

# Prepare embeddings and metadata for these articles
embeddings = np.array(articles_in_kmeans_top_clusters_df['bert_embedding'].tolist())

# Create a list of dictionaries for metadata, including 'text' for the content
metadata = []
for index, row in articles_in_kmeans_top_clusters_df.iterrows():
    metadata.append({
        "doc_id": row['doc_id'],
        "title": row['title'],
        "text": row['cleaned_text'], # Use 'cleaned_text' as the document content
        "cluster_label": row['cluster_label']
    })

# Ensure bert_query_embedding is reshaped for cosine_similarity
query_embedding_reshaped = bert_query_embedding.reshape(1, -1)

# Calculate cosine similarity scores between the filtered article embeddings and the query embedding
scores = cosine_similarity(embeddings, query_embedding_reshaped).flatten()

# Get the indices of the top 5 articles with the highest similarity scores
top_k_idx = scores.argsort()[-5:][::-1] # Indices in the `embeddings` and `metadata` arrays

# Retrieve the actual text for the top articles based on these indices
results = [metadata[i]["text"] for i in top_k_idx]

print(f"Top 5 articles related to the query have been retrieved based on K-Means clustering.")

Top 5 articles related to the query have been retrieved based on K-Means clustering.

In [ ]:
context = "\n\n".join(results)

prompt = f"""
Answer the question using the context below:

Context:
{context}

Question:
{query}
"""

In [ ]:
evidence = [
    {
        "text": metadata[i]["text"],
        "score": float(scores[i])
    }
    for i in top_k_idx
]

In [ ]:
!pip uninstall -y transformers tokenizers
!pip install sentence-transformers
# Please restart runtime after installing new packages.

from sentence_transformers import CrossEncoder

reranker = CrossEncoder('cross-encoder/ms-marco-MiniLM-L-6-v2')
scores = reranker.predict([(query, doc) for doc in results])

Found existing installation: transformers 4.42.0
Uninstalling transformers-4.42.0:
  Successfully uninstalled transformers-4.42.0
Found existing installation: tokenizers 0.19.1
Uninstalling tokenizers-0.19.1:
  Successfully uninstalled tokenizers-0.19.1
Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.12/dist-packages (5.3.0)
Collecting transformers<6.0.0,>=4.41.0 (from sentence-transformers)
  Downloading transformers-5.3.0-py3-none-any.whl.metadata (32 kB)
Requirement already satisfied: huggingface-hub>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (0.36.2)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.10.0+cpu)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.26.4)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.16.3)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.67.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (3.25.2)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (1.4.2)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (6.0.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2.32.4)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Collecting huggingface-hub>=0.20.0 (from sentence-transformers)
  Downloading huggingface_hub-1.8.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2025.11.3)
Collecting tokenizers<=0.23.0,>=0.22.0 (from transformers<6.0.0,>=4.41.0->sentence-transformers)
  Downloading tokenizers-0.22.2-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.3 kB)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.24.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.7.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (0.28.1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->sentence-transformers) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->sentence-transformers) (3.6.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (0.1.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (3.4.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (2.5.0)
Downloading transformers-5.3.0-py3-none-any.whl (10.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.7/10.7 MB 68.3 MB/s eta 0:00:00
Downloading huggingface_hub-1.8.0-py3-none-any.whl (625 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 625.2/625.2 kB 33.4 MB/s eta 0:00:00
Downloading tokenizers-0.22.2-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 71.1 MB/s eta 0:00:00
Installing collected packages: huggingface-hub, tokenizers, transformers
  Attempting uninstall: huggingface-hub
    Found existing installation: huggingface_hub 0.36.2
    Uninstalling huggingface_hub-0.36.2:
      Successfully uninstalled huggingface_hub-0.36.2
Successfully installed huggingface-hub-1.8.0 tokenizers-0.22.2 transformers-5.3.0

Error importing huggingface_hub._snapshot_download: cannot import name 'DryRunError' from 'huggingface_hub.errors' (/usr/local/lib/python3.12/dist-packages/huggingface_hub/errors.py)

ImportError: cannot import name 'DryRunError' from 'huggingface_hub.errors' (/usr/local/lib/python3.12/dist-packages/huggingface_hub/errors.py)

In [ ]:
import pandas as pd
import numpy as np
from supabase import create_client, Client


records_to_upsert = []
for index, row in filtered_df.iterrows():
    records_to_upsert.append({
        "doc_id": row['doc_id'],
        "content": row['cleaned_text'],
        "embedding": row['bert_embedding'],
        "cluster": int(row['hdbscan_cluster_label']),
        "metadata": {
            "title": row['title'],
            "source": row['source'],
            "publish_timestamp": str(row['publish_timestamp']) # Convert timestamp to string for JSONB
        }
    })

try:
    response = supabase.table("article_embeddings").upsert(records_to_upsert, on_conflict='doc_id').execute()
    print(f"Upsert successful. {len(response.data)} records processed.")
except Exception as e:
    print(f"Error during Supabase upsert: {e}")

Error during Supabase upsert: {'message': "Could not find the 'content' column of 'article_embeddings' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}